### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by DonBongJohn** [mediathekview/mediathekviewweb#104]
Give us a dark theme, white websites suck! 

Suggestions:
Background #161618
Text #808080

Rest like icons can stay.
Thanks in Advance.

**Comment by alex1702** [comment]
Lol...

**Comment by bagbag** [comment]
That will come with V2 (whenever that will be), implemented like there (top-left): [https://material.angular.io/](https://material.angular.io/)

**Comment by UweKeim** [comment]
I recommend to detect the [`@media (prefers-color-scheme: dark) `](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) and automatically switch the color scheme to dark.

**Comment by m36** [comment]
Quick and dirty CSS for Stylish:

html, body, .container-fluid, .odd, tr:hover, .input-group, -webkit-tap-highlight-color, .input-group-addon, .form-control, .btn-default, .pagination>li>a, .pagination>li>span, .popover {
    background-color: rgb(28 28 28 / 80%) !important;
    color: #eee !important;
}

**Comment by bagbag** [comment]
24be26f4f3a1b7967a3d1abd354dced642fc9c10
