### ISSUE TITLE
"This site can’t be reached, mediathekviewweb.de took too long to respond."

### ISSUE THREAD

**Issue by hartwork** [mediathekview/mediathekviewweb#105]
Hi!

Not sure if this is the right place to report? The http://www.mediathekweb.de/ website seems to be offline at the moment but I don't see any related ticket. Will it be up again soon?

Thanks and best, Sebastian

**Comment by bagbag** [comment]
Yes that's fine here.

My router/firewall (OPNsense) was dead, at least one part of it. Luckily a simple reboot fixed it.

**Comment by hartwork** [comment]
Awesome, thank you!
