### ISSUE TITLE
"The Cleaners" could not be found in the search (maybe because of content warning?)

### ISSUE THREAD

**Issue by Mofef** [mediathekview/mediathekviewweb#108]
First of all thanks for the good job and thanks for making the content available that I already paid for.

The movie is available here until 15th of september: https://www.arte.tv/de/videos/069881-000-A/im-schatten-der-netzwelt-the-cleaners/
However it couldn't be found was not found by the search of mediatekviewweb. 
I already managed to get the file using jdownloader, but wanted to raise the issue in case you are not aware of it :)

**Comment by bagbag** [comment]
That is not a Issue in MediathekViewWeb, but in the Crawler. Please create a thread in the [Forum](https://forum.mediathekview.de/category/7/fehlende-sendungen) for that.

**Comment by Wikinaut** [comment]
works for me (currently)

![20180910-014146](https://user-images.githubusercontent.com/1151915/45270184-ae7a1600-b49a-11e8-9cd1-59ad2fa3cef6.png)

**Comment by Mofef** [comment]
Thanks for checking! for me it also works now. Maybe since it was broadcasted again last night?
