### ISSUE TITLE
Suggestion: Search operator to hide results with certain search terms

### ISSUE THREAD

**Issue by ta2016** [mediathekview/mediathekviewweb#109]
I'd like to hide search results with certain search terms (like eg. "Audiodeskription") but there is apparently no search operator for that. Could you please add one?

**Comment by derreisende77** [comment]
You can use regexp for that. Questions for that topic will be answered in the forum.

**Comment by ta2016** [comment]
> 
> 
> You can use regexp for that. Questions for that topic will be answered in the forum.

You might want to follow your own advice...

https://forum.mediathekview.de/topic/332/suchkriterien-negieren/8

**Comment by bagbag** [comment]
I am not going to add that to the "old" (current) version of MVW. It's implemented in the next version, which will maybe be released sooner or later, but more likely later.
