### ISSUE TITLE
handle of m3u8 files

### ISSUE THREAD

**Issue by bagbag** [mediathekview/mediathekviewweb#11]
either show info about not being playable (chrome, firefox - edge can handle it) or implement a player that can handle it.

**Comment by styroll** [comment]
Nur zur Info: Safari kann es auch (HLS kommt ja quasi von Apple).

**Comment by bagbag** [comment]
Theoretisch jetzt unterstützt: 05cbe56720cc1edf5f46046b165e4dc70495b163

Aber: 

> Mixed Content: The page at 'https://mediathekviewweb.de/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '[URL]'. This request has been blocked; the content must be served over HTTPS.

**Comment by 0880** [comment]
Ich habe es mit dem Firefox Browser getestet ("Mixed Content Blocking" wurde deaktiviert). Es funktioniert!

**Comment by Wikinaut** [comment]
Könntet Ihr bitte ein konkretes Beispiel angeben ?

**Comment by bagbag** [comment]
!wdr

**Comment by Wikinaut** [comment]
sorry, läuft bei mir nicht:

* debian 8
* Firefox ESR 45.7.0

**Comment by bagbag** [comment]
Ja, davon war auszugehen, da die Standardeinstellungen das nicht erlauben.

**Comment by bagbag** [comment]
Bleibt die Frage wie man das Problem lösen könnte.

1. MVW nicht mehr mit HTTPS anbieten
2. Proxy durch Server
3. Nutzer auffordern Sicherheitseinstellungen zu verringern

**Comment by Wikinaut** [comment]
Ich möchte anheim stellen (vulgo: dringend empfehlen), wenn möglich, ein Popup (Warnung/Info) anzuzeigen.

**Comment by alex1702** [comment]
1 und 3 sind unzumutbar. @bagbag

**Comment by alex1702** [comment]
nutz camo @bagbag kann da ein server von mir aus auch für bereit stellen.

**Comment by Wikinaut** [comment]
Ich meine: Ich möchte anheimstellen (vulgo: dringend empfehlen), wenn möglich, ein Popup (Warnung/Info) anzuzeigen, wenn irgendwas nicht geladen werden kann, wenn das möglich ist...

@alex1702 1. ginge, wenn man für den Download der einen Datei (nach der Suche), den Benutzer entsprechend zur http:// Version von MVW leitet

**Comment by bagbag** [comment]
1. und 3. ist für mich eig. auch keine Option, habe es einfach nur der Vollständigkeit halber aufgezählt.

@Wikinaut 
Hier geht es nicht um den Download, sondern das Anschauen. Download geht ja nach wie vor.

**Comment by Wikinaut** [comment]
(lesen hier ***-Leute mit? Dann sollten wir mal woanders unterhalten.)

**Comment by bagbag** [comment]
Wer soll *** sein?

**Comment by alex1702** [comment]
@Wikinaut klar geht es, ging mir auch nicht ums können, sondern dass es nicht ziel sein sollte einen nutzer zu etwas schlechterem zu zwingen.

**Comment by Wikinaut** [comment]
@bagbag Download geht ? Lass mich kurz probieren...

**Comment by bagbag** [comment]
Ist halt einfach nur die m3u8.

**Comment by Wikinaut** [comment]
@bagbag übrigens sehe ich derzeit - wenn Abspielen nicht ging - "Verbinden......"

**Comment by bagbag** [comment]
Ist bei mir nicht, auch nicht unter Firefox.

**Comment by styroll** [comment]
> @Wikinaut sagte: Funktioniert nicht auf MacOS Sierra 10.12.3 Firefox 51.0.1

security.mixed_content.block_active_content = false, dann klappt's (eben mit SRF-Sendung gecheckt), aber nur das Abspielen, beim DL wird die Playlist runtergeladen (das Master-File).

Der Mehrwert müsste ja im DL bestehen, sehen kann man es auch auf der Sender-Homepage.

**Comment by Wikinaut** [comment]
Download von m3u8 ist unsexy :-))

**Comment by Wikinaut** [comment]
Aber klar.

**Comment by Wikinaut** [comment]
Also, für diese hartnäckigen Dinger nehme ich immer lokal was anders: 
`$was-anderes <url>`

**Comment by bagbag** [comment]
Es werden am tag 500-1000 Videos runtergeladen und etwa 1000 angeschaut.

Wenn wir 200MB pro Video annehmen, wären das 300GB am Tag. Alternativ nur bei m3u8 Videos.

**Comment by bagbag** [comment]
> Wer soll *** sein?

**Comment by 0880** [comment]
>Bleibt die Frage wie man das Problem lösen könnte.
>
>1. MVW nicht mehr mit HTTPS anbieten
>2. Proxy
>3. Nutzer auffordern Sicherheitseinstellungen zu verringern

Es gibt noch eine andere Möglichkeit. Wie ich [hier](https://github.com/mediathekview/mediathekviewweb/issues/40#issuecomment-279855841) schonmal erklärt habe, gibt es 2 Sender die HTTP Live Streaming verwenden: SRF und WDR. Der Sender WDR lässt sich auf direkte MP4 Links umstellen und beim SRF kann man bei den M3U8 Dateien HTTPS verwenden. Momentan werden da noch HTTP Links angezeigt.

Zum Beispiel:

https://mediathekviewweb.de/#query=!SRF

Doku Plus - Design & Destinations - Marokko - HTTP

```
http://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index_5_av.m3u8
```

Doku Plus - Design & Destinations - Marokko - HTTPS

```
https://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index_5_av.m3u8
```


Da die Links aber vom Crawler kommen und du keinen [Einfluss](https://github.com/mediathekview/mediathekviewweb/issues/40#issuecomment-279174642) darauf hast, weiß ich nicht ob sich das umsetzen lässt. Auf diese [Anfrage](https://github.com/mediathekview/MServer/issues/69) gab es bis jetzt keine weitere Rückmeldung.

Damit müssten sich die Mixed Content Probleme eventuell lösen lassen. Wie seht ihr das? Wäre das eine mögliche Lösung?

**Comment by bagbag** [comment]
Zumindest zweites könnte ich dann ja lösen. Einfach zu HTTPS ändern.

Wie sehen denn die mp4 links aus? Eventuell geht das da ja auch. Oder kann man den mp4 Link aus dem Inhalt der m3u8 bekommen?

**Comment by 0880** [comment]
>Oder kann man den mp4 Link aus dem Inhalt der m3u8 bekommen?

Ja, das müsste eigentlich funktionieren. Hier hat @styroll schonmal was geschrieben:

http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=641#p10701

Beispiel:

https://mediathekviewweb.de/#query=!WDR

Der Vorkoster - Pfannkuchen und Waffeln - Master Playlist

```
http://adaptiv.wdr.de/i/medp/ww/fsk0/131/1311767/,1311767_15272401,1311767_15272404,1311767_15272405,1311767_15272402,1311767_15272403,.mp4.csmil/master.m3u8
```
```
http://ondemand-ww.wdr.de/medp/fsk0/131/1311767/1311767_15272401.mp4
http://ondemand-ww.wdr.de/medp/fsk0/131/1311767/1311767_15272404.mp4
http://ondemand-ww.wdr.de/medp/fsk0/131/1311767/1311767_15272405.mp4
http://ondemand-ww.wdr.de/medp/fsk0/131/1311767/1311767_15272402.mp4
http://ondemand-ww.wdr.de/medp/fsk0/131/1311767/1311767_15272403.mp4
```

**Comment by 0880** [comment]
Der erste Teil ist immer gleich: `http://ondemand-ww.wdr.de/medp/fsk0`

Alles andere ergibt sich aus der Playlist.

**Comment by bagbag** [comment]
Man braucht also nicht mal den Inhalt der m3u8 -> ich kann das dann also direkt während dem Indexieren das ganze in die MP4 umformen.

Perfekt, ich danke dir :)

**Comment by 0880** [comment]
Die FSK Angabe muss auch mit übernommen werden.

Zum Beispiel:

WDR - Tatort - Alter Ego

```
http://adaptiv.wdr.de/i/medp/ww/fsk12/130/1301313/,1301313_15152424,1301313_15152427,1301313_15152423,1301313_15152425,1301313_15152426,.mp4.csmil/master.m3u8
```
```
http://ondemand-ww.wdr.de/medp/fsk12/130/1301313/1301313_15152424.mp4
http://ondemand-ww.wdr.de/medp/fsk12/130/1301313/1301313_15152427.mp4
http://ondemand-ww.wdr.de/medp/fsk12/130/1301313/1301313_15152423.mp4
http://ondemand-ww.wdr.de/medp/fsk12/130/1301313/1301313_15152425.mp4
http://ondemand-ww.wdr.de/medp/fsk12/130/1301313/1301313_15152426.mp4
```
Der Tatort hat `fsk12`, die meisten Sendungen allerdings `fsk0`.

```
Diese Sendung ist für Jugendliche unter 12 Jahren nicht geeignet. Das Video darf deshalb nur von 20.00 bis 6.00 Uhr angeboten werden.
```

**Comment by bagbag** [comment]
Zuerst wollte ich beim Parsen HTTP mit HTTPS austauschen, aber dann fiel mir ein, dass ja auch der Inhalt der m3u8 Dateien HTTPS werden muss..

Also wird das ganze ab sofort clientseitig bei jedem XMLHttpRequest ausgetauscht: f74d83a2bd18da4b2e775d0f10442040998fca4a

Und nun geht's an WDR.

**Comment by 0880** [comment]
>Zuerst wollte ich beim Parsen HTTP mit HTTPS austauschen, aber dann fiel mir ein, dass ja auch der Inhalt der m3u8 Dateien HTTPS werden muss..

Der Inhalt der M3U8 Dateien beim SRF ist doch HTTPS.

```
https://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index_5_av.m3u8
```
```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
https://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/segment1_5_av.ts?null=0
#EXTINF:10.000,
https://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/segment2_5_av.ts?null=0
#EXTINF:10.000,
https://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/segment3_5_av.ts?null=0
#EXTINF:10.000,
https://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/segment4_5_av.ts?null=0
#EXTINF:10.000,
https://srfvodhd-vh.akamaihd.net/i/vod/dokplus/2017/02/dokplus_20170217_161317_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/segment5_5_av.ts?null=0

[...]
```

**Comment by bagbag** [comment]
Achso, das wusste ich nicht. Aber nicht schlimm, so funktioniert es ja auch.

**Comment by bagbag** [comment]
Weißt du, ob der Aufbau *immer* `http://ondemand-ww.wdr.de/medp/fsk[x]/[y]/[z]/[q].mp4` ist?

**Comment by 0880** [comment]
Ja, das ist definitiv bei allen Videos so!

**Comment by 0880** [comment]
>Aber nicht schlimm, so funktioniert es ja auch.

Ja, es funktioniert! Die Videos lassen sich nun ohne Probleme abspielen.

**Comment by Wikinaut** [comment]
!srf geht, !wdr geht bei mir nicht.

**Comment by bagbag** [comment]
Logisch, WDR habe ich ja noch nicht implementiert.

> Und nun geht's an WDR.

Sollte in kürze soweit sein.

**Comment by bagbag** [comment]
Soweit funktioniert es (ist noch nicht aufm Server), aber mir ist aufgefallen, dass es URL gibt, die ein klein wenig anders sind: [MVW Query](https://mediathekviewweb.de/#query=Fu%C3%9Fball%203.%20Liga%2C%2023.%20Spieltag%20-%20Konferenz%20%7C%20Fechten%3A%20Der%20L%C3%B6we%20von%20Bonn)

`http://adaptiv.wdr.de/i/medp/de/fsk0/131/1313571/,1313571_15282913,1313571_15282917,1313571_15282915,1313571_15282914,.mp4.csmil/index_2_av.m3u8`
da hat sich zwischen medp und fsk0 noch ein **de** geschlichen. Damit schaff ich es nicht eine MP4 zu bekommen.

**Comment by 0880** [comment]
>Damit schaff ich es nicht eine MP4 zu bekommen.

Ja, das stimmt. Gibt es noch mehr Videos davon (mit **de** in der URL)?

**Comment by bagbag** [comment]
Hab ich noch nicht nachgeschaut.

Wie dem auch sei, WDR rewrite ist online.
Ein weiteres Goodie, dass ich eingebaut habe: Jetzt gibt es auch hohe Qualität 😄

**Comment by bagbag** [comment]
Soweit die Theorie.

> GET http://ondemand-ww.wdr.de/medp/fsk0/131/1313636/1313636_15284445.mp4 net::ERR_BLOCKED_BY_CLIENT

Was ist das denn nun schon wieder? -.-

**Comment by bagbag** [comment]
Die URL ja. Aber ich weiß wieso es nicht ging. Privacy Badger (Browser Addon) hat es blockiert.

**Comment by 0880** [comment]
Dann liegt es am Add-on. Hier funktioniert es ohne Probleme.

**Comment by bagbag** [comment]
[https://mediathekviewweb.de/#query=!wdr%20%2Blokalzeit](https://mediathekviewweb.de/#query=!wdr%20%2Blokalzeit) geht auch nicht.

**Comment by 0880** [comment]
http://www1.wdr.de/mediathek/video/sendungen/lokalzeit/video-lokalzeit--112.html
```
Liebe Nutzer,

leider ist die von Ihnen gewünschte Seite nicht verfügbar. Dies kann mehrere Ursachen haben.
```

Fehler HTTP 404

**Comment by 0880** [comment]
@bagbag 

Das Video ist nicht verfügbar. Du musst den Link zur Mediathek mal aufrufen.

**Comment by bagbag** [comment]
Also, auch geklärt.

Dann noch etwas entdeckt (ich merke, ich sollte MVW auch mal nutzen um Fehler zu entdecken): [https://mediathekviewweb.de/#query=!wdr%20lokalzeit%20bitte&future=true](https://mediathekviewweb.de/#query=!wdr%20lokalzeit%20bitte&future=true)

timestamp: null

**Comment by 0880** [comment]
Ich habe jetzt mehrere Videos getestet. Das Problem mit dem Mixed Content ist durch die Veränderungen erst einmal verschwunden. Ob jetzt in Zukunft noch andere Probleme auftauchen, muss man erstmal abwarten.

Bei den Sendungen mit dem **de** in der URL, müsste man die M3U8 Dateien weiterhin anzeigen.

**Comment by bagbag** [comment]
Das wird es ja. Das Regex das ich erstellt habe hat zufällig dafür gepasst.

**Comment by bagbag** [comment]
So, mit einem timestamp von null wird nun auch umgegangen. Und für heute reichts mir.

**Comment by 0880** [comment]
>http://adaptiv.wdr.de/i/medp/de/fsk0/131/1313571/,1313571_15282913,1313571_15282917,1313571_15282915,1313571_15282914,.mp4.csmil/index_2_av.m3u8

Das sind die direkten MP4 Links:

```
http://ondemand-de.wdr.de/medp/fsk0/131/1313571/1313571_15282913.mp4
http://ondemand-de.wdr.de/medp/fsk0/131/1313571/1313571_15282917.mp4
http://ondemand-de.wdr.de/medp/fsk0/131/1313571/1313571_15282915.mp4
http://ondemand-de.wdr.de/medp/fsk0/131/1313571/1313571_15282914.mp4
```

Das ist das Video mit dem **de** in der URL, was [gestern](https://github.com/mediathekview/mediathekviewweb/issues/11#issuecomment-280873196) nicht funktioniert hat.

**Comment by bagbag** [comment]
Danke dir. Funktioniert jetzt auch damit :)
