### ISSUE TITLE
[Impressum] Placeholders not replaced

### ISSUE THREAD

**Issue by bugwelle** [mediathekview/mediathekviewweb#110]
Visiting https://mediathekviewweb.de/ -> "Über" -> Impressum gives me following content:

```
Impressum
Angaben gemäß § 5 TMG:
{{ name }} 
{{ street }} 
{{ postcode }} {{ city }}

Kontakt:
E-Mail: {{ mail }}
```

Browsers tested: Chrome (latest), Firefox (latest), JavaScript enabled

**Comment by bagbag** [comment]
I'm aware of that, but I didn't feel like fixing that yet. Anyway, thanks for informing me.
