### ISSUE TITLE
Search "!rbb bitte einsteigen" does not work

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#111]
I want to restrict the results of search "bitte einsteigen" to RBB. This appears not to be working today.

**Comment by bagbag** [comment]
The channel is ARD. rbb is in Topic: https://mediathekviewweb.de/#query=Bitte%20einsteigen%20%23rbb

**Comment by Wikinaut** [comment]
uh, yes, ty
