### ISSUE TITLE
Unable to start on Ubuntu 18.10 because of openjfx version - incl. Workaround

### ISSUE THREAD

**Issue by FL140** [mediathekview/mediathekviewweb#112]
First thank' s for the great work so far!

After installing the mediathekview version shipped with Ubuntu 18.10 and running into errors on start (which are already known). I tried to install the latest version 13.2.1 from tar. But there I also ran into an error during start. After backtracing the error it comes down to a `openjfx` version problem.

Ubuntu 18.10 installs version 11 in its `openjfx` package but Mediathekviewweb needs java 8 (which can be installed from default package). No chance to install version 8 of openjfx in parallel from package.

Workaround:
Since I am not too much into Java I found the following workaround and got 13.2.1 running on Ubuntu 18.10. (clean Kubuntu 18.10 ISO in try mode):

* download the `openjfx` packages for Ubuntu 18.04 
openjfx_8u161-b12-1ubuntu2_amd64.deb
libopenjfx-java_8u161-b12-1ubuntu2_all.deb
libopenjfx-jni_8u161-b12-1ubuntu2_amd64.deb

 
# install MediathekView
```
sudo apt --assume-yes install openjdk-8-jre
[[ -f MediathekView-latest.tar.gz ]] || wget https://download.mediathekview.de/stabil/MediathekView-latest.tar.gz
tar -xf MediathekView-latest.tar.gz
sudo chown -R root:root MediathekView-[0-9]*
sudo mv MediathekView-[0-9]* /usr/local/bin/
sudo ln -sf $(cd /usr/local/bin && ls -tr -d MediathekView-[0-9]*|sort|tail -1)/MediathekView.sh "/usr/local/bin/mediathekview"
sudo ln -sf "mediathekview" "/usr/local/bin/MediathekView"
``` 
# MediathekView on Ubuntu 18.10 Workaround
```
DEB_DIR="/isodevice/wrk"
TMP_DIR="/tmp/install_java8_openjfx_workaround"
[[ -d "${TMP_DIR}" ]] || mkdir "${TMP_DIR}"
dpkg -x "${DEB_DIR}/openjfx_8u161-b12-1ubuntu2_amd64.deb" "${TMP_DIR}"
dpkg -x "${DEB_DIR}/libopenjfx-java_8u161-b12-1ubuntu2_all.deb" "${TMP_DIR}"
dpkg -x "${DEB_DIR}/libopenjfx-jni_8u161-b12-1ubuntu2_amd64.deb" "${TMP_DIR}"
sudo cp -r  "${TMP_DIR}/usr/lib/jvm/java-8-openjdk-amd64" /usr/lib/jvm/
sudo cp -r --remove-destination "${TMP_DIR}/usr/share/java/openjfx/"* /usr/lib/jvm/java-8-openjdk-amd64/
```
patch the start script to use Java 8 (replace the start line in MediathekView.sh with):
` 
/usr/lib/jvm/java-8-openjdk-amd64/bin/java  -Xmx2G -jar ./MediathekView.jar "$@"
`

The best solution on the long run would be to migrate to Java 11 from my point of view, but I think the devs will have a good reason to stick with Java 8 at the moment, I think. ;-)

Would it be possible to integrate the needed libs into the shipped package in the meantime?

**Comment by derreisende77** [comment]
Next version will run with Java 11. But there is a lot of work to do to make the app and used libraries working with post Java 9. Linux will also be then the easiest platform to support. Win and Mac are currently showstoppers due to JavaFX not being bundled with a jdk

**Comment by bagbag** [comment]
This is the issue tracker of MediathekView**Web**.
That would be the correct one: [https://github.com/mediathekview/MediathekView](https://github.com/mediathekview/MediathekView).
