### ISSUE TITLE
playlist m3u8 not supported

### ISSUE THREAD

**Issue by Kabelwerker** [mediathekview/mediathekviewweb#115]
"The media could not be loaded because the format is not supported" although data segments are mp4.

Example: Title="Am Schauplatz: Wenn alles zusammenbricht"

**Comment by Kabelwerker** [comment]
Your search result help me find out the link for the playlist.m3ua.
With following html code (videojs.com) i can watch the video for me:
<html>
<body>

<link href="https://vjs.zencdn.net/7.2.4/video-js.css" rel="stylesheet">

<video id='hls-example'  class="video-js vjs-default-skin" width="640" height="360" controls>
<source type="application/x-mpegURL" src="https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-25_2105_sd_02_Am-Schauplatz--_____13993224__o__5337927605__s14385856_6__ORF2HD_21063921P_21542314P_Q6A.mp4/playlist.m3u8">
</video>


<script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.14.1/videojs-contrib-hls.js"></script>
<script src="https://vjs.zencdn.net/7.2.4/video.js"></script>
<script>
var player = videojs('hls-example');
player.play();
</script>
</body>
</html>

**Comment by bagbag** [comment]
[videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) is deprecated and replaced by native support in video.js 7 (i upgraded to it about a month ago).

But I just figured out it's an [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) related issue. I made them to strict.

**Comment by bagbag** [comment]
So I fixed the CSP related stuff and now CORS is kicking in. Unfortunately that's something out of my control (ORF servers). I have to implement a proxy for that, so that all m3u8 requests are routed through my server.

**Comment by bagbag** [comment]
Now it works in Chrome though, but not in Firefox.

**Comment by Kabelwerker** [comment]
Now it is possible to view "!ORF" streams again [tested with Firefox 63.0.1 (64-Bit)].
Thank you very much for this job.
Unfortunately there is no way to get and merge all the *.ts files and store them as one mp4 with the save button.

**Comment by bagbag** [comment]
Oh, it's actually also working in Firefox. It was Privacy Badger (Firefox addon) recognizing their server as tracking. Good, so it's fixed.
