### ISSUE TITLE
FR: permalink for shows

### ISSUE THREAD

**Issue by jtheuer** [mediathekview/mediathekviewweb#116]
First of all, thanks a lot for your great work. I love the simplicity: it just does what you would expect.

I just wanted to share a show with a friend via link and noticed that this isn't supported (the URL always stays the same). Rewriting the URL to sth like `https://mediathekviewweb.de/#play=xyz.hq.mp4` could already help.

Jan

**Comment by bagbag** [comment]
That's something that will be available with MVW 2.0.
