### ISSUE TITLE
ORF: Download links (extraction) broken

### ISSUE THREAD

**Issue by Lukas0907** [mediathekview/mediathekviewweb#118]
Hi,

the extraction of download links is broken for tvthek.orf.at. See for example: https://mediathekviewweb.de/#query=brieflos The downloaded video is a few hundred bytes long.

This seems to also be a problem in youtube-dl, so I think this has been caused by a change in the website.

The extraction in PyFeeds still works, so maybe the code could help you: https://github.com/PyFeeds/PyFeeds/blob/master/feeds/spiders/tvthek_orf_at.py#L20

Thanks,
Lukas

**Comment by bagbag** [comment]
They don't serve full videos anymore, only streams, at least for most of their videos, as [you can see in their API](https://ps_android_v3:6a63d4da29c721d4a986fdd31edc9e41@api-tvthek.orf.at/api/v3/schedule/2018-11-24?page=1&limit=1000).

I looks like PyFeeds do use their stream segments. Unfortunately concatting that in the Browser is not possible, at least not with external urls without CORS.

[I do like one line of code of PyFeeds especially](https://github.com/PyFeeds/PyFeeds/blob/fbb401925f00a940824cd7974b850172e5db90cd/feeds/spiders/tvthek_orf_at.py#L78) 😃

**Comment by Lukas0907** [comment]
Yes, you are right, some links in the API response do not work. One has to carefully choose the right ones, depending on if it's a multi-segment show or not.

> I do like one line of code of PyFeeds especially

Hah, yeah yes, the API is weird and it took some time to figure out which links are actually working. Mediathekviewweb was helpful. :)

For this video https://tvthek.orf.at/profile/Niederoesterreich-heute/70017/Niederoesterreich-heute/13996333 the following link is extracted: https://apasfpd.sf.apa.at/cms-worldwide_episodes/online/b56596132a4a4a34c4885b889bee44ca/1543186800/13996333_0014_Q8C.mp4 (which works)

And for this video (which is not multi-segment) https://tvthek.orf.at/profile/Drive/4656943/Drive-Australien-Rallye/13996356 the following link is extracted: https://apasfpd.sf.apa.at/cms-austria/online/c6317d2b85bbaeb78bea230a2c89e0fe/1543186800/2018-11-25_0915_sd_01_Drive--Australi_____13996356__o__3736816095__s14402380_0__ORF1HD_09151619P_09441807P_Q8C.mp4

**Comment by bagbag** [comment]
> Yes, you are right, some links in the API response do not work. One has to carefully choose the right ones, depending on if it's a multi-segment show or not (I implemented that part in PyFeeds).

That means there is (almost) always a working link?

**Comment by Lukas0907** [comment]
Yes, that should be the case.
