### ISSUE TITLE
Massenweise .ts-Dateien statt einer großen mp4

### ISSUE THREAD

**Issue by cutmycock** [mediathekview/mediathekviewweb#120]
seit kurzem finde ich tausende 1-sekunden-stücke mit suffix .ts. wahrscheinlich meist vom wdr. woran liegt es? senderfehler oder einstellungsfehler in mv oder fehler in mv?
habe neuestes mv und auch alles andere ist brandneu.
wäre schön zu erfahren, woher das kommt und wie man es vermeidet.
![2018-12-01 29 fff](https://user-images.githubusercontent.com/42352389/49327275-cde78300-f55f-11e8-908d-11526a2ec3d3.jpg)

liebe grüße von corinna

**Comment by styroll** [comment]
> @cutmycock sagte: einstellungsfehler in mv oder fehler in mv?
habe neuestes mv

Hier geht es um den Web-Client MVW, nicht MV. Bitte solche Fragen im [Forum von MV](https://forum.mediathekview.de) stellen…
