### ISSUE TITLE
Livestream URLs

### ISSUE THREAD

**Issue by Axel-Erfurt** [mediathekview/mediathekviewweb#121]
Die Livestreams der verschiedenen ARD Sendeanstalten haben alle die gleiche URL,

> http://www.ardmediathek.de/tv/live?kanal=Alle

ebenso bei den ZDF Sendern

> http://www.zdf.de/ZDFmediathek/hauptnavigation/live

Damit funktioniert das Abspielen nicht mehr.

**Comment by bagbag** [comment]
Das hier ist der Issue-Tracker von MediathekView**Web**, das hier gehört entweder ins [Forum](https://forum.mediathekview.de/) oder direkt zum [Issue-Tracker von MediathekView](https://github.com/mediathekview/MediathekView).
