### ISSUE TITLE
Filtern (oder ordnen) nach Dauer

### ISSUE THREAD

**Issue by pglira** [mediathekview/mediathekviewweb#123]
Es gibt eigentlich nur ein feature das ich schmerzlich vermisse: das Filtern, oder zumindest Ordnen, nach der Dauer der Beiträge.

Das Problem sind die vielen sehr kurzen Beiträge (1-5 min) an denen ich in der Regel nicht interessiert bin. Bei den meisten Suchbegriffen überwiegen diese in der Liste der Treffer.

**Comment by bagbag** [comment]
Siehe #66
