### ISSUE TITLE
ORF download links broken

### ISSUE THREAD

**Issue by Clemens-VIE** [mediathekview/mediathekviewweb#127]
The Links for all ORF sources are only a small file with a link to the stram, not the video data itself. It seems that the ORF has changed something in the streaming technology.
![image](https://user-images.githubusercontent.com/48319633/53955388-3010d080-40d9-11e9-8b73-113bcd9403fc.png)
![image](https://user-images.githubusercontent.com/48319633/53955406-3bfc9280-40d9-11e9-8877-4387031c0e6d.png)

**Comment by bagbag** [comment]
ORF only has m3u8 streams since a while. I haven't found a way to get mp4 files.
