### ISSUE TITLE
page offset for rss link not respected

### ISSUE THREAD

**Issue by pejobo** [mediathekview/mediathekviewweb#128]
The rss feed works like a charm but sadly doesn't respect the url parameter "page=<num>". Would this be possibly?

**Comment by bagbag** [comment]
\*rhetorical\* Isn't that somehow "nonsense" for an RSS-Feed?
I guess you want this feature for a tool that downloads the videos?

As the the number of entries returned from the rss feed differs from the page size of the website, I would rather add the parameters "offset" and "count" (or similar). Would that satisfy your needs?

I don't even know why the page parameter gets applied when generating the link.

**Comment by pejobo** [comment]
You're right, this is for a command line tool I intend to write. "offset" and "count" parameters would be great. Then I do not need a dependency to Socket.IO and can stick to plain shell syntax.

**Comment by bagbag** [comment]
You don't need websockets. Look at this: https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de

Might be more useful than an RSS feed.

**Comment by pejobo** [comment]
Yes, this looks great - building a json should be possible even in bash :+1:
