### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by mahibi** [mediathekview/mediathekviewweb#129]
I get the following Error when visiting https://mediathekviewweb.de/

![grafik](https://user-images.githubusercontent.com/2932790/54884564-f5e25580-4e72-11e9-97d0-118e2e00c80f.png)

Firefox 66.0 (64-Bit) on Linux Mint 19.1
I get the error just after updating to Firefox 66.0 and i think before the site worked fine, so this might be a hint.

**Comment by mahibi** [comment]
When clikcing on the Errorcode i see these details:


https://mediathekviewweb.de/

Sichere Kommunikation mit der Gegenstelle ist nicht möglich: Angeforderter Domainname stimmt nicht mit dem Zertifikat des Servers überein.

HTTP Strict Transport Security: true
HTTP Public Key Pinning: false

Zertifikatskette:

-----BEGIN CERTIFICATE-----
MIIFYTCCBEmgAwIBAgISBFpMXC4unsZghYHxWhvEBJXJMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTAzMjQxNzQwMjhaFw0x
OTA2MjIxNzQwMjhaMCAxHjAcBgNVBAMMFSoubWVkaWF0aGVrdmlld3dlYi5kZTCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL6HJelh/eUhszRhFpzpBnXW
HEqLLNFFeZj9GRgvLAfFzvIRci9Cbha09J4pIwci/UtfYhIkfvaC5eIAUprt/S3f
KHVq8uEXiz9E20xszZ5piR4WFZU0zPUlBrTEQxqz791vtF5rMoIdrLOKe6eSSFRD
KLSiGW/+Whzze2A/zGf5t4zzdkAJwvyYIlUV7I69Mf8PBl98G7r9fV8KAfGg9O10
KcurE1SZK7K677V9AVxWVwMS5AFB4x29K72Rna5w8OXlYftbGoLYK0U6QlzD6Ln7
GgYDMAfvoru7ow2tNTqaFvasECfu3FWC7azOH61UKctmvL384ntx+OBCpHZ5FfkC
AwEAAaOCAmkwggJlMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUEiR3LV0SDGCzoj6Z
jV/E1m8NhXIwHwYDVR0jBBgwFoAUqEpqYwR93brm0Tm3pkVl7/Oo7KEwbwYIKwYB
BQUHAQEEYzBhMC4GCCsGAQUFBzABhiJodHRwOi8vb2NzcC5pbnQteDMubGV0c2Vu
Y3J5cHQub3JnMC8GCCsGAQUFBzAChiNodHRwOi8vY2VydC5pbnQteDMubGV0c2Vu
Y3J5cHQub3JnLzAgBgNVHREEGTAXghUqLm1lZGlhdGhla3ZpZXd3ZWIuZGUwTAYD
VR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYa
aHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHx
AO8AdgBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAWmxAQaIAAAE
AwBHMEUCIG4JW64dvQQQFkdgXAYL3WDX2/w2OSTk1unfEXUoedEyAiEAkJBcQdT4
vhwt9P2K9pEcodDT3b2Cu+zBlbsjCX76G2sAdQBj8tvN6DvMLM8LcoQnV2szpI1h
d4+9daY4scdoVEvYjQAAAWmxAQZTAAAEAwBGMEQCIB3qFOz+KsKrLDZeae5hz8lP
xOMcfdNGCGD5SpGyf1ssAiAOC5GACf7r0sO1yPDcbqJ72ypi6aWuPn9CoqY8f6oM
YTANBgkqhkiG9w0BAQsFAAOCAQEAK0b8ijJtmZUQ4CXOoun+oWw3Z8jmlzT8Xqw7
9gMDa4Mww4n6iOTWxFsEC5O33+cuWivTpdmM0+F12b2B5WVtlPXJebFmdyXHgxGB
C3sZOEgegDBxL+DaoEqnsKQWP+usyq9loDw0hONtVWW9jqpeXK9vlhHXunXjW+76
OKRUd9jmpRle13Z3xiN7pbxu5iT3isK9ZbGMTUhoyEYtwu1wYKKaJYXlxHlkDT0P
JWwgiVGqD4H7ByLVRgxdCm2hy0jANmCqL0VknSvtzY76KMjB1RWRb9rXX83AcBgw
nvUlItHXDGW0bWUDn3zl7RqEH6j9mcew9pn9eiYf7+ZAtT2TVg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----

**Comment by mahibi** [comment]
Just visited the site another time (a few minutes later). Now everything works again...

**Comment by Wikinaut** [comment]
@mahibi same here, it did not work, now, the Cert error is gone.

**Comment by bagbag** [comment]
I switched from a certificate for every (sub)domain (13 in total) to wildcard certificates. I wasn't aware, that a certificate for `*.mediathekviewweb.de` isn't valid for `mediathekviewweb.de`, so I had to issue a new multi-domain certificate including the root-domain and wait for the DNS-challenge to complete.

As I was to lazy to temporarily revert all the configuration changes, I decided to wait the 10 minutes for the DNS-challenge to succeed and leave you out in the rain in the meantime 😅
