### ISSUE TITLE
Support for ARTE Concert

### ISSUE THREAD

**Issue by metalmatze** [mediathekview/mediathekviewweb#137]
I can't seem to find any content from ARTE concerts. Are there any plans to support it?
http://arteconcert.com or https://www.arte.tv/de/arte-concert/

**Comment by bagbag** [comment]
What have you searched for?
[https://mediathekviewweb.de/#query=!arte%20%23concert](https://mediathekviewweb.de/#query=!arte%20%23concert)

**Comment by pidoubleyou** [comment]
There is lot of content from ARTE concerts. But I realized the categories Metal/Hip Hop/Electronic are missing. Have a look at https://github.com/mediathekview/MServer/issues/490

**Comment by metalmatze** [comment]
Ha. Yeah, I was searching for Metal concerts. Full Force Festival concerts to be precise.

**Comment by metalmatze** [comment]
Seems like the fix in the other repo was merged. How often do you deploy? Right now I still can't see any results :blush: (I can wait, just asking)

**Comment by bagbag** [comment]
I don't have to deploy anything. As soon as the updated Crawler is deployed (it's not me doing that) and the lists contain the new entries, MVW has them too.

**Comment by alex1702** [comment]
> Seems like the fix in the other repo was merged. How often do you deploy? Right now I still can't see any results blush (I can wait, just asking)

müsste heute drin sein.

**Comment by metalmatze** [comment]
Sweet! Danke, ist alles da! :tada:

**Comment by alex1702** [comment]
> Sweet! Danke, ist alles da! tada

Endlich in deutsch :D

**Comment by metalmatze** [comment]
> > Sweet! Danke, ist alles da! tada
> 
> Endlich in deutsch :D

Super merkwürdig auf GitHub Deutsch zu schreiben :innocent:
