### ISSUE TITLE
Lots of Content Missing from ARTE

### ISSUE THREAD

**Issue by turtlepurple** [mediathekview/mediathekviewweb#139]
Hey There,

Using Mediathekviewweb.de today (10th of August) i couldnt find the content from Arte i was looking for.
The list seems to be new, the first 250 Titles from all stations have the date Aug-10
For !ard there are about 60 titles from Aug-10
For !arte theres only 4 titles since July-30

I'm very glad theres a webversion of mediathekview now, thank you very much!

For Arte for now there's a small bash-script alternative that seems to resolve the links correctly by using the Video-ID: https://sourceforge.net/projects/arte7videodownloader/

**Comment by Nicklas2751** [comment]
Arte just IP blocks us. See here: https://forum.mediathekview.de/topic/2574/arte-sperrt-mediathekview
