### ISSUE TITLE
Zeitraum-Filter übereifrig

### ISSUE THREAD

**Issue by PaulWoolley6710** [mediathekview/mediathekviewweb#141]
MediathekView (13.3 sowie 13.5) such nur 30 Tage rückwirkend, auch wenn im "Zeitraum"-Kasten das "unendlich"-Symbol steht.
(MacOS Version 10.12.6)

**Comment by derreisende77** [comment]
1. Dies hier sind issues für MediathekViewWeb, nicht MediathekView.
2. Nein, MediathekView filtert ohne Fehler. Evtl mal den Tagesfilter verkleinern und auf unendlich stellen (Der Juli ist älter als 30 Tage):
![Bildschirmfoto 2019-10-13 um 18 47 47](https://user-images.githubusercontent.com/8466092/66718988-4955ca00-edea-11e9-89e4-60c99bac99b7.jpg)
