### ISSUE TITLE
Running mediathekvieweb with docker

### ISSUE THREAD

**Issue by ralfi** [mediathekview/mediathekviewweb#144]
Hi there,

i try to run mediathekview local with the docker image from hub.docker.com. Of course there are a instance of elasticsearch 6.8.3 and one redis instance with open ports 9200, 9300 and 6379 at localhost. Can anyone give me useful hints for the config.js in the docker container to run the docker image?

Thanks!

**Comment by bagbag** [comment]
If you're running elasticsearch and redis directly on the host you have to use host networking for the MVW container.

Here is a stack template I use for mediathekviewweb.de
https://gitlab.com/patrickhein/server-cluster/blob/master/roles/docker-management/files/stacks/mediathekviewweb/stack-template.yaml

**Comment by ralfi** [comment]
Thanks, this works after a little bit of adjusting config.

**Comment by ralfi** [comment]
Hi Patrick, do you have a hint to setup a http proxy in this use case with docker?
