### ISSUE TITLE
Allow to exclude items via "-" (e.g. "-Hörfassung")

### ISSUE THREAD

**Issue by TheZoker** [mediathekview/mediathekviewweb#151]
First: Nice project, really like it!

When I search for "Tatortreiniger" I want to exclude the "Hörfassung":
https://mediathekviewweb.de/#query=!ndr%20%23tatortreiniger

Please add the option to exclude some items in the search result (similar to google by using "-Hörfassung" or something similar). So i could use "!ndr #tatortreiniger -Hörfassung".

Another useful scenario would be "-Audiodeskription". 

This would especially be nice for the RSS feed.

**Comment by pejobo** [comment]
This would be really great!

**Comment by bagbag** [comment]
I won't implement this in V1. If I finish V2 one day, you'll have that. It's already implemented in that codebase.
