### ISSUE TITLE
Indexing fails in docker environment please help to debug these

### ISSUE THREAD

**Issue by ralfi** [mediathekview/mediathekviewweb#154]
Hi there,

i am trying to setup mvw / elasticsearch / redis in my docker environment for selfhosting. 

It seems to me that all fine but getting filmlist do not work. From my mvw shell i have a working connection to the redis image and to the elasticsearch 6.8.3 image on port 9200 (curl -v http://<elasticimage:9200) works well. There are no errors on the mvw console but the index cannot found.

![grafik](https://user-images.githubusercontent.com/294423/73741104-db8f2e80-4749-11ea-8f5d-967eaee0e874.png)

Calling the Web-Interface i receive this

![grafik](https://user-images.githubusercontent.com/294423/73740993-9b2fb080-4749-11ea-81b1-1b71c4e7ec05.png)

How can i debug this to find a a solution?
Thanks in advance!

**Comment by bagbag** [comment]
Get the mvw-app container using `docker ps`. Then use `docker logs {id}` to receive the logs of mvw.

Providing your docker-compose.yml would also help. That's the one I use for <https://mediathekviewweb.de>: <https://gitlab.com/patrickhein/server-cluster/-/blob/master/roles/docker-management/files/stacks/mediathekviewweb/stack-template.yaml>

**Comment by ralfi** [comment]
Hi bagbag,
thanks for the link, using this it works well. Seems to be a syntax error
