### ISSUE TITLE
medias in other languages are not shown?

### ISSUE THREAD

**Issue by jeyca** [mediathekview/mediathekviewweb#163]
I tried to find https://www.arte.tv/en/videos/085382-000-A/darwin-downtown/ which you can find in english Arte.tv part, but its not possible to find in mediathekviewweb.de, is there a way to download medias like this?

**Comment by Nicklas2751** [comment]
Please use the forum for requests like this: https://forum.mediathekview.de/category/7/fehlende-sendungen
