### ISSUE TITLE
get links by api?

### ISSUE THREAD

**Issue by ezzra** [mediathekview/mediathekviewweb#164]
is there already a way to request the data via an api link, for example as json output? I know the apps goal is to be a webfrontend, but as the data is there it would be nice to fetch it this way too :)

**Comment by bagbag** [comment]
Take a look at that: [https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de](https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de)

**Comment by faulesocke** [comment]
Does this need any special headers normally only sent by browsers? I tried replicating this using python (should be a no-brainer) but I always error messages from the server saying:
```python
 {'result': None, 'err': ['Unexpected token o in JSON at position 1']}
```

Code:
```python
import requests

url = "https://mediathekviewweb.de/api/query"
query = {
    "queries": [
        {
            "fields": ["title", "topic"],
            "query": "sturm der liebe",
        },
    ],
    "sortBy": "timestamp",
    "sortOrder": "desc",
    "future": True,
    "offset": 0,
    "size": 10,
}

#query = """{"queries":[{"fields":["title","topic"],"query":"sturm der liebe"},{"fields":["channel"],"query":"ndr"}],"sortBy":"timestamp","sortOrder":"desc","future":false,"offset":0,"size":10}"""

res = requests.post(url, json=query)
req = res.request
req.body, res.json()
```

I'm sure I did something stupid wrong but I can't find what. :/

**Comment by bagbag** [comment]
Thats actually not a problem on your side, but on my. Use the header "Content-Type: text/plain" and it should work.

**Comment by MrFly72** [comment]
Searching for „Topic“ „Filme im Ersten“ delivers only Part of the results through API. Any clue?
