### ISSUE TITLE
Filmlisten (z.B. ZDF Die Bergretter) nicht aktuell

### ISSUE THREAD

**Issue by GerhardTatschl** [mediathekview/mediathekviewweb#171]
Hello,

Till some weeks ago there was no problem to download ZDF-films, e.g. "Die Bergretter"

When I search for "Die Bergretter", I only get dates to 6.6.2020.
But not 13.6.2020 ord 20.6.2020 - on these dates ZDF played also "Die Bergretter" and i find these films in the zdf-mediathek.

What's wrong here ?

**Comment by DaDirnbocher** [comment]
I think it would be better to ask questions like this (missing films) in https://forum.mediathekview.de/category/7/fehlende-sendungen
