### ISSUE TITLE
ARD Doctor Who Der Tag des Doktors (Special zum 50. Jubiläum)

### ISSUE THREAD

**Issue by michaelno55** [mediathekview/mediathekviewweb#177]
Ein falscher Film ist im mediaview am 18 August 2020 unter Doctor Who Der Tag des Doktors (Special zum 50. Jubiläum)
abgespeichert.

**Comment by andreygursky** [comment]
Die URL-Links auf den falschen Film sind in der ARD Mediathek abgespeichert. MediathekView hat nur die Links kopiert, die in der Tat jetzt falsch sind.
