### ISSUE TITLE
Vorschaubild für Sendungs-Suche 

### ISSUE THREAD

**Issue by Matthias84** [mediathekview/mediathekviewweb#178]
Ich nutze MVV um Sendungen und Themen zu folgen und gelegentlich auch zu recherchieren. Mir fiel auf, dass die Sender oft ja Vorschaubilder für die Sendungen haben, diese aber in den Suchergebnissen nicht mit angezeigten werden. Viele andere Medienportale wie Youtube / Vimeo / Peertube / media.ccc.de / ... stellen Bilder für ihre Suchen auch da, weshalb ich von einem recht verbreiteten UI Patterm sprechen würde. 

Ich weiß nicht, ob Mediathekenview solche Infos schon auswerten kann. Die Mediatheken haben auf der Seite einer Folge oft opengraph HTML Elemente mit dem Vorschaubild. Andernfalls könnte man in den Folgen-Listen schauen bzw. das thumbnail aus dem gestoppten Player-Element nutzen.

**Comment by andreygursky** [comment]
Die auf Wunsch einschaltbaren und ggf. lazy-loaded Vorschaubilder vermisse ich auch.

In meinen Bash-Scripts bekomme ich sie wie folgt:
* ARTE
  * JSON
   ```https://api-cdn.arte.tv/api/mami/v1/program/de/$ID/1280x720```

* ZDF & Co
  * JSON
   ```jq -r '.teaserImageRef.layouts["1280x720"]' -- "${JSON_FILENAME}"```

* ARD
  * JSON
  ```wget -O - "https://api.ardmediathek.de/page-gateway/pages/ard/item/$ID" | jq -r '.widgets[0].mediaCollection.embedded._previewImage'```
  - HTML
   ```wget -O - "https://www.ardmediathek.de/ard/player/$ID" | grep __FETCHED_CONTEXT__ | sed -e 's| *window.__FETCHED_CONTEXT__ = \({.*}\);|\1|g' | jq -r ' .[] | select(.widgets!=null) | .widgets[0].mediaCollection.embedded._previewImage'```

Die Bildauflösung lässt sich noch in beide Richtungen anpassen. ARTE ist wieder vorbildlich: kurz und einfach.

**Comment by DaDirnbocher** [comment]
Gibt doch schon ein [Issue ](https://github.com/mediathekview/mediathekviewweb/issues/167)dazu, warum noch eines aufmachen?

**Comment by bagbag** [comment]
Doppelt -> #167
