### ISSUE TITLE
Arte Serie ist online aber nicht in MediathekViewWeb

### ISSUE THREAD

**Issue by MalEbenSo** [mediathekview/mediathekviewweb#180]
Hallo.

Die Serie "Kampf um den Halbmond" ist bei Arte online, taucht aber nicht in MediathekViewWeb auf.

https://www.arte.tv/de/videos/RC-019886/kampf-um-den-halbmond/
bzw. 
https://www.arte.tv/de/videos/089025-001-A/kampf-um-den-halbmond-1-8/
https://www.arte.tv/de/videos/089025-002-A/kampf-um-den-halbmond-2-8/
https://www.arte.tv/de/videos/089025-003-A/kampf-um-den-halbmond-3-8/
...

Danke und Gruß.

**Comment by MalEbenSo** [comment]
Alle Videos sind per https://www.savethevideo.com/ runterzuladen.
D. h. mein konkretes Anliegen hat sich erledigt. 

Ich werde den Eintrag dennoch nicht schließen, falls ein Entwickler der Sache dennoch nachgehen möchte, warum dieser Download nicht funktioniert. 

PS Danke für ein tolles Programm.

**Comment by Nicklas2751** [comment]
Das wäre ein Thema für das Forum gewesen. Noch dazu sucht MediathekviewWeb nicht selbst nach Filmen sondern nutzt, wie alle MediathekView Clients, die Filmliste vom MServer (Crawler).

Das Nächste mal hier: https://forum.mediathekview.de/category/7/fehlende-sendungen

**Comment by MalEbenSo** [comment]
Danke für den Hinweis. Werde ich ich das nächste Mal beherzigen.

**Comment by MalEbenSo** [comment]
Nachtrag nur zur Info: Auch für MediathekViewWeb ist das Problem gelöst. Oben rechts ist eine Option "zukünftige". Wenn dieser Schalter aktiviert ist, dann erscheinen die Filme.

Den Schalter habe ich bisher nie beachtet. Meine Erwartung war, dass damit angekündigte aber noch nicht verfügbare Inhalte auftauchen. Das will ich nicht, also habe ich ihn ausgeschaltet gelassen. 
Tatsächlich sind die gesuchten Inhalte ("Kampf um den Halbmond", auch "Babylon Berlin" ist betroffen) bereits verfügbar und werden damit in MediathekViewWeb sichtbar. 
Leider habe ich im Hilfe-ReadMe keine Beschreibung gefunden, was der Schalter eigentlich bewirken soll.

**Comment by styroll** [comment]
>@MalEbenSo sagte: Oben rechts ist eine Option "zukünftige". Wenn dieser Schalter aktiviert ist, dann erscheinen die Filme.
Die Option ist jetzt per default aktiv.

>@MalEbenSo sagte: Leider habe ich im Hilfe-ReadMe keine Beschreibung gefunden, was der Schalter eigentlich bewirken soll. […] Meine Erwartung war, dass damit angekündigte aber noch nicht verfügbare Inhalte auftauchen.
Hm, gibt's diesen Fall überhaupt? Angekündigt und **via API ausgeliefert** wird doch erst etwas, wenn wenigstens ein Trailer da ist. D.h. da ist dann sehr wohl etwas verfügbar…

**Comment by MalEbenSo** [comment]
Ob die Erwartung realistisch ist oder nicht sei dahingestellt. Sie ist auf jeden Fall falsch, wie ich jetzt dazugelernt habe.

Mein Hinweis ging vor allem in die Richtung, den Schalter "zukünftige" zu dokumentieren. Das kann kann entweder auf der Hilfeseite erfolgen …
https://github.com/mediathekview/mediathekviewweb/blob/master/README.md
… oder leichtgewichtiger: So wie ein Mouse-over zur "Suche" eine kleine Hilfestellung einblendet, könnte das auch hier (und bei anderen Schaltern) geschehen.
