### ISSUE TITLE
Änderung in der Readme.md

### ISSUE THREAD

**Issue by Mr-Phil1** [mediathekview/mediathekviewweb#181]
Lieber Projekt-Betreiber,
mir ist in der ReadMe im FAQ-Bereich ein kleiner Fehler aufgefallen. Dort wird noch in das alte und geperrte Repo vom youtube-dl verwiesen, dieses wurde Mitte Oktober auf drängen der DCMA gesperrt.

**Comment by alex1702** [comment]
Die Frage ist worauf will man jetzt zeigen?

**Comment by bagbag** [comment]
Auf [https://youtube-dl.org/](https://youtube-dl.org/)

**Comment by Mr-Phil1** [comment]
Oder auf:

- https://github.com/lrvick/youtube-dl
- https://github.com/FuckRIAA/youtube-dl

**Comment by NoNamePro0** [comment]
Ja, diese sind aber nur ältere Mirrors von dem Projekt. https://youtube-dl.org/ ist die offizielle Seite von dem Projekt, dort wird wohl auch ein neues Repository angekündigt
