### ISSUE TITLE
Thema mit mehreren Wörtern

### ISSUE THREAD

**Issue by jlelse** [mediathekview/mediathekviewweb#182]
Ich benutze MWV um mehreren Sendungen per RSS-Feed zu folgen. Allerdings hab ich nicht rausgefunden, wie es möglich ist den Themenfilter (`#`) für ein Thema mit mehreren Wörtern zu benutzen, damit auch wirklich nur Videos von diesem Thema in der Suche erscheinen.

Wäre es außerdem möglich einen Negativfilter hinzuzufügen um Videos mit bestimmten Wörtern im Titel herauszufiltern? Bei manchen Sendungen gibt es auch Videos mit Audiodeskription.

Vielen Dank für dieses großartige Projekt!

**Comment by bagbag** [comment]
[https://github.com/mediathekview/mediathekviewweb#das-komma-ist-der-und-operator](https://github.com/mediathekview/mediathekviewweb#das-komma-ist-der-und-operator)

[https://mediathekviewweb.de/#query=sturm%2Cder%2Cliebe](https://mediathekviewweb.de/#query=sturm%2Cder%2Cliebe)

Negativfilter werden in dieser Version nicht mehr kommen. Sollte ich V2 irgendwann fertig machen, dann wird es dort vorhanden sein (das Feature ist da schon fertig implementiert).
