### ISSUE TITLE
"Zukünftige"

### ISSUE THREAD

**Issue by ueen** [mediathekview/mediathekviewweb#183]
Einige bereits verfügbare Filme werden erst angezeigt wenn man die "Zukünftige" Chekbox anwählt, aktuelles Beispiel:
https://mediathekviewweb.de/#query=%C3%96kozid //Film wird nicht angezeigt
https://mediathekviewweb.de/#query=%C3%96kozid&future=true //Film wird angezeigt
Ist das so gewollt? Erscheint mir zumindest irgendwie nicht logisch.

**Comment by andreygursky** [comment]
"Zukünftige" bezieht sich auf Datum/Zeit, die mediathekviewweb anzeigt. Für die zukünftigen Sendungen soll das mit dem geplanten Ausstrahlungstermin übereinstimmen.

> commented 18.11.2020 14:11 GMT+1

Somit war "18.11.2020 20:15" in der Tat in der Zukunft.

**Comment by ueen** [comment]
Der Film war ja bereits verfügbar, wäre es nicht möglich das auch abzufragen, wenn Ausstrahlungstermin in Zukunft aber in Mediathek bereits verfügbar => normal anzeigen? :)

**Comment by andreygursky** [comment]
Ich habe das nicht überprüft, deshalb ist es an dieser Stelle meine Vermutung. Mediathekview kann nur solche zukünftige Sendungen anzeigen, die nicht nur angekündigt sondern auch vom Sender bereits vorab in die Mediathek gestellt wurden. Somit wäre jede zukünftige Sendung, die von Mediathekview angezeigt wird, ab sofort verfügbar. Es kommt also nur auf die Frage, welche Voreinstellung für "zukünftige" Checkbox - "an" oder "aus" - eher Erwartungen der Mehrheit der Nutzer entsprechen würde.

**Comment by ueen** [comment]
Ah ok, dann würd ichs entfernen, ich fands verwirrend und hab bestimmt 15min gesucht bevor ich drauf gekommen bin, weil in der Mediathek findet mans ja auch direkt, ist dann unglogisch wenns in MediathekenView nicht auftaucht. Man könnte ja auch auf "Noch nicht ausgestrahlte ausblenden" ändern, aber keine Ahnung warum man das wollen würde :D

**Comment by bagbag** [comment]
Die Idee dahinter war, dass man ohne Filter einen "Live-Feed" hat, was gerade läuft. Aber wahrscheinlich ergibt es wirklich Sinn den Filter einfach zu entfernen.

**Comment by ueen** [comment]
Denk ich auch, alternativ kann man ja ein label einführen "vorab" oder eben den Filter umgkehren "Noch nicht ausgestrahlte ausblenden"

**Comment by ueen** [comment]
s. https://github.com/mediathekview/mediathekviewweb/pull/187
