### ISSUE TITLE
Zdf ab 23 11.2020 nicht  vorhanden

### ISSUE THREAD

**Issue by evusoft** [mediathekview/mediathekviewweb#185]
Zdf ab 23 11.2020 nicht  vorhanden

**Comment by DaDirnbocher** [comment]
Ich habe 50 Einträge nach dem 23.11.2020. Ganz abgesehen davon, dass das "Datum" hier eine eigene Bedeutung hat und zukünfitge Einträge mit älteren Daten gelistet sein kann, z.B: die Schwarzwaldklinik: AUsstrahlung in der Zukunft, gelistet mit 2016/2017.
