### ISSUE TITLE
Access Denied Error when downloading "Luther"

### ISSUE THREAD

**Issue by 18iteration** [mediathekview/mediathekviewweb#189]
![grafik](https://user-images.githubusercontent.com/45468984/100443626-585d1180-30aa-11eb-8ff4-8f796edd50b5.png)

This error only occurs when trying to download "Luther" , regardless of quality selection.

I suppose this is due to the fact that the show only aired on a specific timeframe and thus was removed afterwards? (Given it's popularity)

**Comment by bagbag** [comment]
Yes, that's an error message from the zdf mediathek and not from MVW. They likely depublished it and we cannot do anything against it.
