### ISSUE TITLE
Datum 10 Jahre in der Zukunft

### ISSUE THREAD

**Issue by Zitronella** [mediathekview/mediathekviewweb#190]
Ruft man https://mediathekviewweb.de/ ist der Haken jetzt ja standardmäßig bei "Zukünftige" gesetzt
Der erste Beitrag verweist auf
"SpiO"-Talk mit Marcus Burghardt
https://www.ardmediathek.de/ard/video/sport-im-osten/-spio--talk-mit-marcus-burghardt/mdr-de/Y3JpZDovL21kci5kZS9iZWl0cmFnL2Ntcy9mZjMzYzMxMC0wMjczLTQzMDktODllZi03MTI0OTFjZmE3ZTM/
Auf der ARD Seite ist der Beitrag mit Datum
"SpiO"-Talk mit Marcus Burghardt
19.08.2020 ∙ Sport im Osten ∙ mdr.de 
Video verfügbar:
bis 19.08.2021 ∙ 10:37 Uhr
Auf mediathekviewweb.de wird als Datum 19.08.20**30** angegeben. 
![01](https://user-images.githubusercontent.com/14326582/101408421-abba3580-38dc-11eb-984a-78accbc3c53a.png)
![02](https://user-images.githubusercontent.com/14326582/101408434-ae1c8f80-38dc-11eb-9fed-d2a5fefd4c69.png)

**Comment by styroll** [comment]
>@zitronella sagte: Auf mediathekviewweb.de wird als Datum 19.08.2030 angegeben.

Daten wie das Datum werden via API abgegriffen, nicht aus einer Webseite ausgelesen. Die API liefert hier offenbar das falsche Datum.
