### ISSUE TITLE
Suppress Referer when following Link

### ISSUE THREAD

**Issue by Flexperte** [mediathekview/mediathekviewweb#192]
Problem: 
Some providers (namely ORF) are now blocking requests for the video stream based upon the "Referer:" being "https://mediathekviewweb.de/". 

Reproduce: 
– Open an ORF video link in a separate Tab/Window -> Request is denied by the server
+ Klick once in the address field of that video and confirm the URL by pressing Return, as if you just typed it (do not just Reload the page!). Because that clears the Referer, the video will load now. 

Resolve: 
Please add code to suppress the Referer: Header from the Request to the target server.

**Comment by bagbag** [comment]
94a8f528abfe334f57cc758b1f89d37ef9cf623d
