### ISSUE TITLE
Feature request: Servus TV

### ISSUE THREAD

**Issue by tobip** [mediathekview/mediathekviewweb#193]
Ich möchte hier den Vorschlag für eine zusätzliche Quelle einbringen, den österreichischen Privatsender Servus TV:

https://www.servustv.com

Ich würde ja auch gerne was dazu beitragen, hab allerdings von TypeScript keine Ahnung...

**Comment by alex1702** [comment]
Privat Sender nehmen wir nicht auf. https://mediathekview.de/faq/#wird-das-programm-um-die-mediathek-des-senders-xyz-erweitert
