### ISSUE TITLE
4K content available in the source?

### ISSUE THREAD

**Issue by blueicehaller** [mediathekview/mediathekviewweb#198]
Hello,
it seem that 4K content is available via HbbTV only e.g. 

- [12. Staffel "Der Bergdoktor" kann in 4K & HDR gestreamt werden - 4K Filme](https://www.4kfilme.de/12-staffel-der-bergdoktor-kann-in-4k-hdr-gestreamt-werden/)
- ["Bergretter" und "Traumschiff" in hochauflösender Qualität : ZDF Presseportal](https://presseportal.zdf.de/pressemitteilung/mitteilung/in-der-zdfmediathek-die-bergretter-und-das-traumschiff-in-hbbtv-in-hochaufloesender-uhd-und-hdr/)
- [ZDFMediathek 4K-HDR Video download - Loewe friends](https://www.loewe-friends.de/viewtopic.php?t=9112)

Do the feeds from the providers you connect to (ZDF in this case) already provide 4K resolution or is this limited to HbbTV?

http://hbbtv.zdf.de/zdfm3/index.php provides me only the option for SD and HD.

Maybe I need to use user agent switcher?

- https://deviceatlas.com/blog/list-smart-tv-user-agent-strings
- http://webostv.developer.lge.com/discover/specifications/web-engine/

Or do I need to use it in combination with https://github.com/karl-rousseau/HybridTvViewer ?

Thank you in advance.

**Comment by bagbag** [comment]
We should be able to get that too, but that's something which has to be done in another project, where I get the data from: [https://github.com/mediathekview/MServer](https://github.com/mediathekview/MServer)

**Comment by blueicehaller** [comment]
@bagbag Do I need to duplicate this issue to the mentioned project or does such an request exist there?

**Comment by bagbag** [comment]
@blueicehaller I've updated the issue about HDR content to 4K and HDR
