### ISSUE TITLE
Ergebnisliste nach Sender Suche fehlerhaft

### ISSUE THREAD

**Issue by dmtask** [mediathekview/mediathekviewweb#203]
Wenn ich z.B. nach "ARD" suche finde ich keine Sendungen von heute (17.03.3021). Wenn ich den Filter raus nehme, werden mir entsprechende Sendungen angezeigt. Das scheint mir ein Bug zu sein...

**Comment by bagbag** [comment]
Nach Sender filtern geht auch ein klein wenig anders:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/4116942/111457945-20411380-8719-11eb-8886-bbf76a20ef60.png">

<https://mediathekviewweb.de/#query=!ard>
