### ISSUE TITLE
export to csv file - data analytics

### ISSUE THREAD

**Issue by wkdata** [mediathekview/mediathekviewweb#223]
Hello, could you please implement a new function? It would be very useful to export the results in csv-file, in order to analyze the data (for data science/analytics).

I know I could use python to scrape the data, but an implimented function would be more flexible.

Thank you very much.

Respectfully
WK

**Comment by bagbag** [comment]
No, that will not happen. But you can use the [JSON API](https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de).
