### ISSUE TITLE
Verlinktes ARD/WDR-Video ist weitaus kürzer

### ISSUE THREAD

**Issue by TheChatty** [mediathekview/mediathekviewweb#225]
Das [verlinkte Video](https://wdrmedien-a.akamaihd.net/medp/hbbtv/weltweit/fsk0/256/2564030/2564030_39676480.mp4) wird in MTVW mit 29min angegeben, ist aber nur 3min lang.

**Comment by DaDirnbocher** [comment]
Vielleicht ergänzt Du ja noch um welche Sendung es sich handelt. Ich konnte auf die Schnelle jetzt keine Sendung mit 29 min finden, bei der - aktuell - dieses 3 min verlinkt sein sollte. 

Auch wenn ich die Filmliste nach (Teilen) der URL durchsuche, finde ich keinen passenden Eintrag.  Insofern neige ich zu der Einschätzung, dass es sich -. wenn - um ein temporäres Problem gehandelt hat.

**Comment by TheChatty** [comment]
[Diese Suche](https://mediathekviewweb.de/#query=sparkasse) fördert für den 28.10. folgendes zu Tage:
![image](https://user-images.githubusercontent.com/4789510/148796712-ce8ed7cc-e64a-4e4b-9d76-b75f49671c15.png)
Das verlinkte Video ist jedoch nur 3min30 lang:
![image](https://user-images.githubusercontent.com/4789510/148796891-dcc7afe5-06e8-40b0-8d34-ff9d6e9b93d9.png)

**Comment by DaDirnbocher** [comment]
Das ist offensichtlich ein Teilbeitrag der Sendung vom 28.10., bei dem - aus welchen Gründen immer - die Länge der gesamten Sendung dortsteht. Solche "Fehler" kommen immer wieder mal vor, und ich würd einmal vermuten, dass die Dauer da von der ARD so geliedert wird.

Aber was ist Dein konkiretes Anliegen? Wennst die ganze Sendung haben willst, nimmst den Eintrag mit dem Titel "Frau tv | 28.10.2021". Wennst eh nur den Einzelbeitrag willst hast ihn eh.

**Comment by TheChatty** [comment]
Ich habe kein gesteigertes Interesse am Beitrag oder Sendung. Aber dieser Fehler ist evtl. noch bei anderen Sendungen vorhanden. Er ist nicht schlimm, aber wenn die Dauer schon angezeigt wird, sollte es doch die korrekte sein.

**Comment by DaDirnbocher** [comment]
Wie erwähnt nehmen die MV-Crawler Daten aus den Mediatheken, d.h. der Fehler liegt (genauer: lag) vermutlich bei der ARD und müßte daher dort korrigiert werden. Dazu kommt, dass es sich um einen mehrere Monaten alten Eintrag handelt, bei dem meines Wissens nur mehr die Erreichbarkeit der URL überprüft wird und solange die erreichbar ist, bleibt der Eintrag in der Liste. Also bräuchts für eine Korrektur auch einen Fluxkompensator. ;-)

**Comment by TheChatty** [comment]
Wenn der Fehler in der ARD-Mediathek lag, dann machen wir hier zu.
