### ISSUE TITLE
API gives "Bad Request"

### ISSUE THREAD

**Issue by moridius** [mediathekview/mediathekviewweb#230]
I'm trying to use the API but I always get error 400, Bad Request.

I read [this gist](https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de) and tried to do the same in Python:

```
#!/usr/bin/env python3

import urllib.request

query = {
    "queries": [
        {
            "fields": ["title", "topic"],
            "query": "sturm der liebe"
        }
    ],
    "sortBy": "timestamp",
    "sortOrder": "desc",
    "future": False,
    "offset": 0,
    "size": 10,
    "duration_min": 20,
    "duration_max": 100
}

data = urllib.parse.urlencode(query).encode("utf-8")
with urllib.request.urlopen("https://mediathekviewweb.de/api/query", data) as f:
    print(f.read().decode("utf-8"))
```

Did the API change or am I missing something here?

**Comment by bagbag** [comment]
You're probably missing `Content-Type: text/plain`. Yes, it's wrong and stupid, but it is what it is right now.

**Comment by moridius** [comment]
That was actually part of the problem (and also my JSON was wrong...). Thanks!

**Comment by pflaf** [comment]
How did you solve the problem?
I tried this:

`import requests
import json

url = 'https://mediathekviewweb.de/api/query'
query = {
         "queries": [],
         "sortBy": "timestamp",
         "sortOrder": "desc",
         "future": False,
         "offset": 0,
         "size": 1000,
         "duration_min": 90
         }


queryString = json.dumps(query, separators=(',', ':'))  # hopefully equivalent to JSON.stringify()
answer = requests.post(url, json=queryString)
print(answer)  # <Response [400]>
print(json.loads(answer.content))  # {'result': None, 'err': ['Unexpected token o in JSON at position 1']}`

As you can see I also get Response 400. I additionally get this "unexpected token o in JSON"-error and I don't know where it comes from.

I did some adaptions to the query, but I get the same output for your query. It also doesn't make any difference if I add "content-type": "text/plain" or if I remove it.

**Comment by pflaf** [comment]
I just noticed, that I get the same error if I just do
`import requests
import json

url = 'https://mediathekviewweb.de/api/query'

answer = requests.post(url)
print(answer)  # <Response [400]>
print(json.loads(answer.content))  # {'result': None, 'err': ['Unexpected token o in JSON at position 1']}
`
