### ISSUE TITLE
Subtitles for ARTE

### ISSUE THREAD

**Issue by ldlx** [mediathekview/mediathekviewweb#237]
I searched for "Diener des Volkes", which has one episode on ARD and all others on ARTE. Only for the one on ARD the subtitles are available in MediathekViewWeb, but not for ARTE, although they are visible on arte.tv.

Would it be possible to provide the ARTE subtitles as well? Thank you very much!

**Comment by styroll** [comment]
To what ARTE videos of this series are concerned, the subtitles are burnt in. If you refer to separate subs, please [read this](https://github.com/mediathekview/MServer/issues/791#issuecomment-1030844894) in the MServer project (providing the crawlers digging the URL of videos and subs and creating the list (Filmliste) used by MVW (and MV).

**Comment by ldlx** [comment]
Thank you!
