### ISSUE TITLE
RSS-Feed: size does not match hd-url

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/mediathekviewweb#259]
The feed contains the hd-url if it exists, otherwise the normal url.
But as size is always given the normal one.

[example](https://forum.mediathekview.de/post/32539)

**Comment by bagbag** [comment]
<https://forum.mediathekview.de/post/32552>

> Das Problem hier ist, dass die Filmliste (die Ursprungsquelle der Daten in MVW) nur die Dateigröße für die mittlere Qualität beinhaltet. Grob gesagt habe ich hier also schlicht nicht die nötigen Daten, um die Größe für die höhere Qualität mitzugeben.
>
> ```Aber in MVW werden auch größen für niedrige und hohe Qualität angezeigt!1!!```
> Ja, weil hier bei Bedarf (User öffnet den Popup eines Eintrags) die Dateigröße bei ARD/ZDF/etc. abgefragt wird.
Das ist für den Feed jedoch keine Option, da das sonst zu viele Requests wären.
Hier war mein Motto also: Lieber einheitlich die Größe der mittleren Qualität, als gar keine - So hat man zumindest einen groben Anhaltspunkt.
