### ISSUE TITLE
Server nicht erreichbar 502 Bad Gateway

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/mediathekviewweb#260]
Routenvervolgung landet bei

 3    19 ms    18 ms    18 ms  f-ed11-i.F.DE.NET.DTAG.DE [62.154.17.154
 4    18 ms    18 ms    18 ms  80.156.161.186
 5    20 ms    20 ms    20 ms  ae1-0.bbr01.anx84.nue.de.anexia-it.net [
 6    82 ms    68 ms    21 ms  netcup-gw.bbr01.anx84.nue.de.anexia-it.n
 7    19 ms    23 ms    20 ms  dcr02.netcup.net [46.38.252.33]
 8    22 ms    22 ms    21 ms  s02.cloudful.de [185.232.69.119]

Ablaufverfolgung beendet.

**Comment by bagbag** [comment]
Die Route passt. Elasticsearch hatte sich verabschiedet.
