### ISSUE TITLE
Request Limit → RSS

### ISSUE THREAD

**Issue by SebastianBerlin** [mediathekview/mediathekviewweb#268]
Gibt es ein **Request Limit** für die Funktion des **RSS-Feeds**? Falls ja, was wird gewünscht?

**Comment by bagbag** [comment]
Nein, gibt kein Limit. Solange der Server nicht explodiert ist es mir im Prinzip egal. Wie viele Requests pro Minute schweben dir denn vor?

**Comment by bagbag** [comment]
Das ist gar kein Problem. Eine Handvoll kannste auch alle paar Sekunden machen.
