### ISSUE TITLE
ZDF-Mediathek-Download zerstört WLAN-Netz

### ISSUE THREAD

**Issue by Fragesteller** [mediathekview/mediathekviewweb#271]
Seit einigen Wochen habe ich große Probleme mit Downloads aus der ZDF-Mediathek.
Unabhängig davon, ob ich Firefox, FreeDownloadManager oder jDownloader benutze,
das gesammte WLAN-Netz bricht 3-4 mal pro Datei zusammen.
Nur die Windows-Netzwerkproblembehandlung hilft dann bis zum nächsten Zusammenbruch.
Ich habe bereits den WLAN-Stick und den Router ausgetauscht, ohne Änderung.
Was mache ich falsch?

**Comment by d0x7** [comment]
Irrelevant was das Problem ist, hat es nichts hiermit zutun. Unnötig für sowas eine Issue zu öffnen meiner Meinung nach.

**Comment by Nicklas2751** [comment]
Einerseits sind wir nicht die ZDF Mediathek d.h. wenn du MediathekView überhaupt nicht nutzt bist du hier vollkommen falsch.

Aber auch beim ZDF bzw. deren Bereich für die Mediathek ist dein Anliegen falsch. Wenn dein WLAN Probleme hat melde dich bei einem IT Service o.ä. die sich um deinen PC bzw. deinen Router kümmern. Welche Seite du aufrufst und was du versuchst zu laden ist dafür vollkommen irrelevant.

Issue closed 🔒
