### ISSUE TITLE
Speicher-Button lädt Film im Browser statt Speichern-Dialog aufzurufen

### ISSUE THREAD

**Issue by MalEbenSo** [mediathekview/mediathekviewweb#275]
Wenn ich auf das Speichern-Symbol (Diskette) klicke, öffnet sich der Film im Browser statt den Speichern-Dialog aufzurufen.

Das Verhalten ist bei Firefox, Brave und Safari identisch.

Als Workaround kann ich rechts-klicken auf das Disketten-Symbol und dann im Kontextmenü "Link speichern unter …" auswählen.

**Comment by DaDirnbocher** [comment]
Das ist kein Mediathekviewweb thema sondern eines deines browsers. im firefox z.B. kann man einstellen, wie ff wie dateien/links verfahren soll: (vereinfacht gesagt) speichern oder abspielen:

![image](https://github.com/mediathekview/mediathekviewweb/assets/11771553/08ae0467-192c-47ad-bacc-eb01a4ce687f)

**Comment by MalEbenSo** [comment]
Danke für die schnelle Antwort.

Verstanden … teilweise. 😉

Zum einen finde ich in Brave und Safari keine vergleichbare Einstellung. Das heißt, die Nutzer dieser Browser haben Pech?

Außerdem leuchtet mir nicht ein, warum dann zwei Buttons da sind, einer zum Anschauen, der andere mit Diskettensymbol.

**Comment by DaDirnbocher** [comment]
Da fragst du wohl besser in Brave und/oder Safari-Foren nach. Ist ja ein Browser-Thema.

**Comment by bagbag** [comment]
Der Speicher-Button gibt den Hinweis "bitte downloaden" an den Browser. Diese können aber frei entscheiden das zu ignorieren. Manche machen das bspw. bei Fremd-Domains (wie es bei MVW mit den Videodateien der Fall ist).

**Comment by MalEbenSo** [comment]
Ist die von MediathekViewWeb genutzte Implementierung, den Hinweis "bitte download" zu geben, die einzig mögliche?

Ich frage deshalb, weil ich bei einer anderen Webseite (save.tv) dieses Problem nicht habe, mit keinem Browser:
- Der Knopf fürs Streaming streamt
- Der Knopf fürs Downloaden öffnet den "Sichern unter …"-Dialog

Ich bin kein Web-Entwickler. Aber das legt für mich nahe, dass es eine Methode geben, die in Browsern zuverlässig zum gewünschten Verhalten führt.

**Comment by bagbag** [comment]
Ohne save.tv genauer angeschaut zu haben (da Registrierung notwendig): Der Unterschied dürfte sein, dass save.tv innerhalb der eigenen Domain agiert, während MVW den Download Cross-Origin verlinkt (da sind Browser allgemein sehr viel restriktiver und in diesem Thema definitiv auch, das hatte ich schonmal genauer untersucht).
