### ISSUE TITLE
Filme werden nicht angezeigt, obwohl in MediathekView und MTPlayer vorhanden

### ISSUE THREAD

**Issue by wallobit** [mediathekview/mediathekviewweb#287]
Einige Filme z.B. die Filmreihe von Lars von Trier auf Arte werden nicht angezeigt. Beispiel Dogville, Manderlay etc.
MediathekView und MTPlayer zeigen sie jedoch an. Benutzen MediathekView und MediathekViewWeb nicht dieselbe Datenbasis?
MediathekViewWeb scheint damit nicht klarzukommen. Könnte vielleicht ein grundlegendes Problem sein, nicht nur bei den o.a. Filmen.
Ergänzung: Betrifft auch andere Filme außerhalb der Reihe Lars von Trier. Beispiel: Lex Barker - Westernheld und Playboy

**Comment by dadidadit** [comment]
@bagbag
So auch hier:
https://mediathekviewweb.de/#query=!ZDF%20%23Spielfilm-Highlights%20%2Btod%20in%20Sev
(und auch von der ARD mit Datum vom 01.10.2023)

Könnte es evtl. damit zusammenhängen, dass dzumindest dieser Film erst nach 23 Uhr gesehen werden kann?
Siehe auch   https://forum.mediathekview.de/topic/5392/fehlende-filme

In der Filmliste vom 03.10.2023 13:33 Uhr sind sie vorhanden.
Verfügbar ist der Film bis 08.10.23

Ard: https://www.ardmediathek.de/video/Y3JpZDovL3pkZi5kZS9QUk9EMS9TQ01TX2M5NjU3YWNmLTU5OGUtNGI1ZC04ZWY5LWY4OTI0MjA3OTRhYQ

ZDF:
https://www.zdf.de/filme/spielfilm-highlights/tod-in-sevilla-108.html

**Comment by bagbag** [comment]
Offenbar ist eine Indizierung vor kurzem fehlgeschlagen und darauf hin haben die Deltas/inkrementelle Updates nicht mehr gepasst. Habe es jetzt einmal komplett neu indizieren lassen und siehe da, sind mehr Einträge geworden.
