### ISSUE TITLE
RBB Abendschau seit 01.10. nicht mehr gelistet

### ISSUE THREAD

**Issue by Cimbass** [mediathekview/mediathekviewweb#288]
Seit dem 01.10. wird die rbb24 Abendschau (und viele andere RBB Sendungen) nicht mehr aufgelistet oder gefunden.

**Comment by dadidadit** [comment]
Das ist ein Gerücht.  Überprüfe deine Filter.

**Comment by Cimbass** [comment]
Interessanterweise gehts jetzt auf einmal tatsächlich ohne jegliche Änderung "meiner Filter".
