### ISSUE TITLE
Performance Probleme

### ISSUE THREAD

**Issue by MrFly72** [mediathekview/mediathekviewweb#289]
Kann es sein, dass MVWeb seit einigen Gagen. Mit massiven Performanceproblemen zu kämpfen hat?
Es scheint irgendwie nicht rund zu laufen?
Oder geht es nur mir so?

**Comment by bagbag** [comment]
Ist/war nicht nur bei dir so. Irgendjemand oder etwas hat MVW mit requests zugebombt. Hab jetzt mal ein Rate-Limit sowohl auf Reverse-Proxy als auch Applikations Ebene eingerichtet.

Ich hoffe, dass das so erstmal ausreicht.

**Comment by MrFly72** [comment]
Jetzt geht bei mir gar nichts mehr ....
Bekomme direkt beim api ein Gateway error 502.

**Comment by bagbag** [comment]
*Jetzt* gerade oder vor wenigen Minuten?

Du kannst eine Mail an kontakt@mediathekviewweb.de schreiben.

**Comment by MrFly72** [comment]
Habe dir mal meine IP geschickt.
Die ist seit ca. 1-2 Jahren fix.

**Comment by MrFly72** [comment]
Ansonsten läuft es bei mir wieder besser. Habe bis jetzt auch keinen Error mit einem Request Throttle auf meine Anfragen bekommen. Denke mal du würdest sonst einen 429 schicken oder?

**Comment by bagbag** [comment]
Genau.

**Comment by MrFly72** [comment]
Dann merke ich ja wenn es "dir" zu viel wird. Wie gesagt sind es bei mir so ca. 20-30 Sendungen, extra nicht parallel angefragt (bei ard + zdf mache ich das um die HD Größe zu ermitteln, da mach ich die HEAD Anfragen mit bis zu 20 threads parallel.)

**Comment by bagbag** [comment]
Ich habe das Limit jetzt mal aus dem Bauch heraus auf 150 Requests pro Minute gesetzt. Ich will da legitime Nutzung ja gar nicht limitieren, sondern nur falls jemand/etwas durchdreht (sei es absichtlich oder unabsichtlich), ein Riegel vorsetzen.

**Comment by MrFly72** [comment]
Alles klar, das sollte langen, denke ich. Ich hab gerade auch mal die Liste der Sendungen etwas ausgedünnt/aufgeräumt 😂
Habe es eh vor einiger Zeit schon aufgetrennt in Gruppen:
Kinder / Krimis / Serien / Herzkino / Dokus
So kann ich gezielter Abfragen, weil nicht alles immer upgedated wird.
Ist ja auch so, dass ich zwar 30-40 Sendungen abfrage aber gerade aktuell noch nicht wobei jeder neue Folgen da sind.
