### ISSUE TITLE
Seit Tagen teilweise gravierende Serverprobleme

### ISSUE THREAD

**Issue by wallobit** [mediathekview/mediathekviewweb#290]
Seit einigen Tagen ist der Aufruf der Seite problematisch:

- Javascript-Meldung kommt für einige Sekunden, obwohl eingeschaltet
- Das System hängt ab und zu an dieser Stelle bis ca. 30 Sekunden oder es geht gar nichts mehr
- Suchbegriffe werden nicht aktualisiert, bei manueller Aktualisierung Verbindung ganz verloren
- Diverse "Hänger" an unterschiedlichen Stellen
- Unterschiedliche Schweregrade dieser Probleme zu unterschiedlichen Zeiten, manchmal auch wieder anscheinend keine Probleme

Haben das mit mehreren Betriebssystemen, Browsern und Internetzugängen über Tage getestet.

![1](https://github.com/mediathekview/mediathekviewweb/assets/61207195/1ae7341e-94f1-4bdd-bc95-bd8a4f4b9399)
![2](https://github.com/mediathekview/mediathekviewweb/assets/61207195/10c9b7fb-e7c7-4149-8f28-efb909c26d5d)
![4](https://github.com/mediathekview/mediathekviewweb/assets/61207195/eb3a6d92-dab3-493a-bffb-f6249bbf0c8d)
![3](https://github.com/mediathekview/mediathekviewweb/assets/61207195/ffe7e796-82a1-4870-8771-53e56349e590)

**Comment by bagbag** [comment]
> @bagbag Seit gestern Abend bestehen wieder solche massiven Performanz-Probleme,[ vgl. Forum](https://forum.mediathekview.de/post/37289).

Sollte jetzt wieder laufen

**Comment by styroll** [comment]
>@bagbag sagte: Sollte jetzt wieder laufen

Ging ja super schnell. Besten Dank dafür und generell für deine Arbeit für diesen tollen Webdienst.
