### ISSUE TITLE
Add operator to exclude things

### ISSUE THREAD

**Issue by henningaround** [mediathekview/mediathekviewweb#308]
Just like the title says...

For example I personally would like to exclude everything containing "Audiodeskription" in its title.

**Comment by DaDirnbocher** [comment]
siehe [hier](https://github.com/mediathekview/mediathekviewweb/issues/91#issuecomment-357771732)

**Comment by henningaround** [comment]
Yes 😊

**Comment by henningaround** [comment]
See https://github.com/mediathekview/mediathekviewweb/issues/91#issuecomment-357771732
