### ISSUE TITLE
Polyfill.io is considered malicious.

### ISSUE THREAD

**Issue by vulewuxe86** [mediathekview/mediathekviewweb#312]
Polyfill.io is considered malicious.

Source: https://www.golem.de/news/angriff-via-polyfill-io-ueber-100-000-webseiten-verbreiten-ploetzlich-malware-2406-186452.html

https://github.com/mediathekview/mediathekviewweb/blob/7a40be207a81ad3ceac317888a80f196d6928ff2/client/index.html#L22

**Comment by bagbag** [comment]
fixed by #a7ae4c80e8f161bb2a79d8f2b1f603d79909449f
