### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#38]
re: https://github.com/mediathekview/mediathekviewweb/wiki/Running-Server 

$ sudo npm run build

> mediathekviewweb@1.0.0 build /var/www/html/mediathekviewweb
> babel index.js --out-file ./static/index-compiled.min.js --source-maps

/usr/bin/env: ‘node’: No such file or directory

npm ERR! mediathekviewweb@1.0.0 build: `babel index.js --out-file ./static/index-compiled.min.js --source-maps`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the mediathekviewweb@1.0.0 build script.
npm ERR! This is most likely a problem with the mediathekviewweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel index.js --out-file ./static/index-compiled.min.js --source-maps
npm ERR! You can get their info via:
npm ERR!     npm owner ls mediathekviewweb
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /var/www/html/mediathekviewweb
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by Wikinaut** [comment]
On the wiki page, please add after step 3 (or add in the requirements)
```
$ npm install babel-cli
````

And on my fresh debian-9 system, after installation
```
$ sudo apt install nodejs
```

I needed to add a symbolic link
```
$ ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by bagbag** [comment]
I've never had that error.

As your node and npm is quite old, I suggest install it from [https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

**Comment by Wikinaut** [comment]
Oh yes. Done. Now I got:
```
node app.js
server listening on *:8000

downloading filmliste...
download error: EACCES: permission denied, open '../filmliste.xz'
download failed...
```

because your code apparently wants to download the filmlist.xz to the **parent** directory which is not nice (and which has a different owner on my system. When setting to the same onwer, this error goes away.)

**Comment by bagbag** [comment]
you can change it in config.hson

**Comment by Wikinaut** [comment]
better to start with a default value inside the code directory, e.g. `"data/filmliste"`.

**Comment by Wikinaut** [comment]
Now, after downloading I got this Elasticsearch failure
http://dpaste.com/3PSGXQ9.txt
and then ES is not running any more...

**Comment by bagbag** [comment]
What Elasticsearch version are you running?

**Comment by Wikinaut** [comment]
The lastest as described on their repo page https://www.elastic.co/guide/en/elasticsearch/reference/master/deb.html

```
{
  "name" : "dImROrs",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "XXXXXXXXXXX",
  "version" : {
    "number" : "5.2.0",
    "build_hash" : "24e05b9",
    "build_date" : "2017-01-24T19:52:35.800Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by bagbag** [comment]
To be honest, I have no clue what this could be.
You waited a few seconds after starting ES and before starting mvw? (as ES has to start..)
Correct port (even though 9200 should be default)?

**Comment by Wikinaut** [comment]
What is your node user ? I started `node app.js` as user, and the whole directory was set to user:user

**Comment by bagbag** [comment]
I created an extra user for MVW.

**Comment by Wikinaut** [comment]
I will need some time. It's the first time I installed Elasticsearch, and redis-server, and will try to find the issue and report back here.

**Comment by bagbag** [comment]
I can help you via teamviewer/similar stuff if you want.

**Comment by Wikinaut** [comment]
@bagbag my Elasticsearch problem _could_ be caused by the very tiny 1&1 Cloud Server I have set up for this test. It has only 0.5 GB RAM.... I will try to set it up on my other machine and close this issue.

**Comment by bagbag** [comment]
That could it be. It uses 1.5GB on my server.

**Comment by Wikinaut** [comment]
My other server shows the same problem.

**Comment by bagbag** [comment]
what is the log of elasticsearch saying?

**Comment by Wikinaut** [comment]
The second server says 
```
$ systemctl status elasticsearch
...
elasticsearch[37903]: Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME
```

but `java -version` looks fine

**Comment by Wikinaut** [comment]
uuuhh:
```
There is insufficient memory for the Java Runtime Environment to continue.
Feb 10 21:10:50 opteryx elasticsearch[54182]: # Native memory allocation (malloc) failed to allocate 2060255232 bytes for committing reserved memory.
```

**Comment by Wikinaut** [comment]
giving up here.

**Comment by Wikinaut** [comment]
may be a solution to reduce heap size
https://www.elastic.co/guide/en/elasticsearch/reference/master/heap-size.html

**Comment by bagbag** [comment]
/etc/elasticsearch/jvm.options

try putting

`-Xms200m
-Xmx1500m
`

in it. Thats what I use on server.

**Comment by Wikinaut** [comment]
I tried this already in the meantime. May be another problem, too, because the second server has Java 7, Java 8 installation failed (debian 8), need to look to this later.

On the first server, I now decreased the heap values to 1g.
Get this: http://dpaste.com/13JW53Z.txt

**Comment by Wikinaut** [comment]
Any idea, why the indexer (this is my understanding) cannot find the filmliste (error 404) see http://dpaste.com/13JW53Z.txt ?

**Comment by bagbag** [comment]
Elasticsearch seems to have no index called "filmliste".

try clearing redis `redis-cli flushall` and restart mvw.

**Comment by Wikinaut** [comment]
same problem

**Comment by bagbag** [comment]
may I can take a look via teamviewer or similar software?

**Comment by Wikinaut** [comment]
no

**Comment by bagbag** [comment]
Does it work now?

**Comment by Wikinaut** [comment]
no. I was waiting for some ideas from your side... 

In the meantime I tried to define a different filename like "data/xxxfilename", or "../xxxfilename" and found, that the changed names are not reflected in the error mssages, which still say "filename".

**Comment by bagbag** [comment]
You mean [http://dpaste.com/13JW53Z.txt](http://dpaste.com/13JW53Z.txt) that error?

Its always "filmliste" because I create a Index called "filmliste" it has nothing to do with the file.

**Comment by bagbag** [comment]
`sudo cat /var/log/elasticsearch/elasticsearch.log`

what's in it?

**Comment by Wikinaut** [comment]
here's the last relevant content http://dpaste.com/0KKY8Y9.txt

**Comment by Wikinaut** [comment]
max number of threads too low ?

**Comment by bagbag** [comment]
It should only be important for performance, but shouldn't make it not working.

**Comment by bagbag** [comment]
I'll create a vm later (you're using Debian 9?) and try it myself, writing down what I do.

**Comment by Wikinaut** [comment]
Yes, debian 9.

**Comment by Wikinaut** [comment]
I tried this https://www.elastic.co/guide/en/elasticsearch/reference/master/max-number-of-threads.html - both methods are not working for me.

as root:

`ulimit -u 2048; systemctl start elasticsearch.service`

error message still the same
`[dImROrs] max number of threads [1841] for user [elasticsearch] is too low, increase to at least [2048]`

**Comment by bagbag** [comment]
Woot. I get the same error about "filmliste".

**Comment by bagbag** [comment]
I guess its because of [https://github.com/mediathekview/mediathekviewweb/blob/4cac370ac487598265337819277b0878cdb64454/MediathekIndexer.js#L141](https://github.com/mediathekview/mediathekviewweb/blob/4cac370ac487598265337819277b0878cdb64454/MediathekIndexer.js#L141)

As the Database is new, there is no filmliste index, so it's not found and can't be deleted.
And as I had no error checking in begin, it was ignored when I've set it up on my server and just worked. How ironic :D

**Comment by bagbag** [comment]
I've updates Install Guide: [https://github.com/mediathekview/mediathekviewweb/wiki/Running-Server](https://github.com/mediathekview/mediathekviewweb/wiki/Running-Server)

**Comment by Wikinaut** [comment]
(Ich dachte mir schon so 'was...)

Thanks, indexing worked. I see the static elements, but not yet the dynamic parts. Will try to fix this tomorrow (Morgen ist auch noch ein Tag).

Thanks so far.

**Comment by Wikinaut** [comment]
Most likely, because I accessed the static page via Apache. Need to access to the node server, either via a proxy or by port address to the node server, I guess.

**Comment by Wikinaut** [comment]
@bagbag ok! Server up and running!

Can you allow me write access to the wiki pages ?

I wanted to add some information how to run it either with Apache reverse proxy or without apache, and that the server port (e.g. 8000) is defined and can be changed in in config.hjson.

From https://stackoverflow.com/questions/18947356/node-js-app-cant-run-on-port-80-even-though-theres-no-other-process-blocking-t  there is this useful information for those souls who want to run the node server on port 80:
`$ sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8000`

**Comment by bagbag** [comment]
Try now.

**Comment by Wikinaut** [comment]
Yes, works.
I also want to ad some infos how to deploy the MVW as a service. I already use successfully instructions from https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service for my Etherpads, which I will modify for mvw use.

**Comment by Wikinaut** [comment]
See https://github.com/mediathekview/mediathekviewweb/wiki/Running-MediathekViewWeb-as-a-service for information how to run MVW as a service.

**Comment by bagbag** [comment]
As I mentioned in your pull-request (#47), using PM2 is all we need.
