### ISSUE TITLE
HLS Master Playlist und MP4 Links

### ISSUE THREAD

**Issue by 0880** [mediathekview/mediathekviewweb#40]
Wenn man nach "!WDR #WDR aktuell" sucht, wird in der Auswahl statt der "Master Playlist" nur die jeweilige "Variant Playlist" angezeigt. Wäre es möglich zusätzlich die Master Playlist anzuzeigen, um dann mit externen Tools (Livestreamer, Streamlink, VLC, ...) darauf zugreifen zu können?

Angezeigt wird folgendes (WDR aktuell vom 10.02.2017):

Mittel:

```
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/index_2_av.m3u8
```
Niedrig:

```
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/index_0_av.m3u8
```

Die Sortierung ist fehlerhaft. Playlist "index_0_av.m3u8" (512x288) hat eine höhere Auflösung als die Playlist "index_2_av.m3u8" (320x180).

Das sind allerdings nur zwei verfügbare Auflösungen. Die Master Playlist beinhaltet alle Auflösungen (auch 960x540).

```
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/master.m3u8
```
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=529000,RESOLUTION=512x288,CODECS="avc1.77.30, mp4a.40.2"
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/index_0_av.m3u8?null=0
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1661000,RESOLUTION=960x540,CODECS="avc1.77.30, mp4a.40.2"
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/index_1_av.m3u8?null=0
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=177000,RESOLUTION=320x180,CODECS="avc1.66.30, mp4a.40.2"
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/index_2_av.m3u8?null=0
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=310000,RESOLUTION=480x270,CODECS="avc1.66.30, mp4a.40.2"
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/index_3_av.m3u8?null=0
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=56000,CODECS="mp4a.40.2"
http://adaptiv.wdr.de/i/medp/ww/fsk0/130/1307723/,1307723_15222589,1307723_15222588,1307723_15222590,1307723_15222591,.mp4.csmil/index_2_a.m3u8?null=0
```
Direkte Links gibt es auch.

```
http://ondemand-ww.wdr.de/medp/fsk0/130/1307723/1307723_15222588.mp4
```

Warum werden diese Links eigentlich nicht angezeigt?

**Comment by bagbag** [comment]
Auf die Links habe ich leider keinen Einfluss, die kommen von der Filmliste des Hauptprojektes MediathekView.

Ich werde das weitergeben und dir dann hoffentlich eine Antwort geben können. Ich danke dir für den Hinweis :)

**Comment by bagbag** [comment]
Ich habe mir erlaubt das ganze im richtigen Projekt zu nennen: [https://github.com/mediathekview/MServer/issues/69](https://github.com/mediathekview/MServer/issues/69)

**Comment by 0880** [comment]
Es ist tatsächlich ein Fehler in der Filmliste. Habe die Liste (Filmliste-akt.xz) jetzt manuell runtergeladen und überprüft, da ich das Programm nicht verwende, sondern nur über den Browser auf MediathekViewWeb.de zugreife.

**Comment by styroll** [comment]
> @0880 sagte: Es ist tatsächlich ein Fehler in der Filmliste.

Nein, es ist – wenn schon – ein Fehler beim WDR. Das Problem ist, dass "index_2" üblicherweise  die "960x540"-Version ist.

**Comment by 0880** [comment]
@styroll 

Hab es jetzt nochmal mit einer anderen Sendung versucht und da ist es tatsächlich so, das die Playlist "index_2_av.m3u8" die höchste Auflösung hat. Würde trotzdem vorschlagen, auf direkte MP4 Links umzustellen, da Firefox kein HTTP Live Streaming abspielen kann und ich die Sendungen extern mit einem anderen Tool und der Master Playlist abspielen muss.

**Comment by styroll** [comment]
>@0880 sagte: Würde trotzdem vorschlagen, auf direkte MP4 Links umzustellen

In diesem geschlossenen Thread und bei MVWeb bist du mit deinem Anliegen am falschen Ort. Hier ist der richtige Ort: https://github.com/mediathekview/MServer/issues/69

**Comment by styroll** [comment]
Vielleicht probierst du mal dieses [FF-Add-on](https://addons.mozilla.org/de/firefox/addon/native-hls).

**Comment by Wikinaut** [comment]
@styroll No more add-ons, please.

**Comment by styroll** [comment]
Dann könnte ich jetzt auch sagen: No more Web-Clients please.

Wenn man den HLS-Support serverseitig (via JS) plant (vgl. bestehende Issue), ist das auch nicht viel anderes, als ein bestehendes Add-on (welches auch nichts anderes auf dem Client macht) einzusetzen, mal abgesehen vom Aufwand. Das beste wäre, wenn der Browser nativ HLS unterstützen würde. Und die Unterstützung von De-facto-Standards war noch nie eine Stärke von Mozilla…

**Comment by Wikinaut** [comment]
@styroll Da gebe ich Dir recht, native Support beim FF war immer schlecht.  Ich hoffe auch, dass man die Downloads hinbekommt...

**Comment by 0880** [comment]
Sowohl Chrome (Desktop Version), als auch Firefox unterstützen es nicht. Soweit ich das sehen kann, gibt es laut Filmliste (ohne die Livestreams) zwei Sender die HTTP Live Streaming verwenden: SRF und WDR. Den WDR könnte man (wenn eine Implementierung möglich ist) auf direkte MP4 Links umstellen.

Generell sollten die Anforderungen für die User so gering wie möglich sein. Zusätzliche Add-ons will ich nicht installieren.

**Comment by bagbag** [comment]
Am Anfang habe ich [Video.js](http://videojs.com/) genutzt, es aber aufgrund von Skalierungsproblemen (zumindest habe ich es nicht auf die Reihe bekommen) verworfen und den einfach `video` tag genutzt.

Da es [HLS unterstützt](https://github.com/videojs/videojs-contrib-hls), werde ich es wohl nochmal probieren. Untertitel können dann auch gleich eingebaut werden. Ebenso ein Auswahlfeld für die Qualität.

**Comment by Wikinaut** [comment]
Nur zur Info, was ich dauernd von den Radiosendern erhalten, wenn ich Sie daraufhin anspreche, dass sie FLASH (Teufelswerk!) erfordern (der letze Absatz, Markierung von mir hinzugefügt, ist der böseste):


<Zitat>
Sehr geehrter Herr ....,

vielen Dank für Ihr Interesse an unserem Sender Deutschlandradio. 

Bei den Musiksendungen und Hörspielen wurden einige Änderungen vorgenommen.
Früher durften wir aus rechtlichen Gründen nur in Ausnahmefällen diese Formate online anbieten.

Mittlerweile dürfen wir einige Musiksendungen und Hörspiele online zum Nachhören anbieten.
Hierbei nutzen wir das neue technische Protokoll HLS (http Live Streaming).

Es handelt sich hier zwar nicht um einen Live-Stream, wie der Name suggeriert, sondern um ein on-demand abrufbares Audio, jedoch ist das Übertragungsprotokoll identisch. Normalerweise übertragen wir unsere on-demand-Audios einfach per http, das heißt, es wird einfach eine mp3-Datei vom CDN (Content Delivery Network) abgerufen. Mit der Verwendung von HLS ist es in der Regel nicht einfach mehr möglich eine Audiodatei mit „rechte Maustaste – speichern unter“ herunter zu laden. 

**Es handelt sich hierbei also um eine technische Barriere, damit wir Musiksendungen und Hörspiele rechtlich zum Nachhören, jedoch nicht mehr zum Download anbieten können. Konkret ist es auf den meisten Desktop-Plattformen (Windows 7, Linux) erforderlich, dass das Flash-Plugin installiert ist. Ohne Flash lassen sich die HLS-Audios nicht abspielen.**

Gruß aus Köln
(Name entfernt)
Hörerservice 
</Zitat>

**Comment by Wikinaut** [comment]
Also: ladet runter, solange es immer geht.
