### ISSUE TITLE
[Suggestion] Show age of Filmliste, filmlist download age, and/or local index age

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#42]
I suggest some improvements of the bottom line
"Die Suchmaschine brauchte 37.71 ms, zeige Treffer 1 bis 15 von insgesamt 162524 Treffern."

* localisation: replace decimal point "." with "," - for those language where this apply like German
* add age of the filmliste, at least the download date to the MVW server
* add index age (if this is relevant for the end user. As an end user, I am only interested in the "effective age" of the data which I can search, but when it comes to playing a video, it's the availability of the video. Because I don't currently know what is possible, I filed the two dates here.)

**Comment by bagbag** [comment]
1. done: eed66a5d6c3ad2ab086fd6323d54183d431d29f9
2. done: 5c473369a552f2cd5bf3bcddc9083cf904d2cd04
3. absolutely not relevant I would say.
