### ISSUE TITLE
[Clarification request] Is the heavy Elasticsearch really needed ?

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#45]
Have you considered to use a different, or even no search engine?

Just a question... because on my small server I just saw more than 7.000(!) seconds indexing (when I set the heap to 200mb minimum / 1000mb maximum). With 1500m/1500 it took 700 seconds.

**Comment by bagbag** [comment]
At begin I used simple Sets/Hashlists build in on node. Then I switched to Redis and build my own searchengine on it. But it takes a lot of time to improve, it's not flexible...
Elasticsearch is awesome. The results are very good, it's fast, .... I will not change it unless you have an better solution, which I doubt.

Then something is wrong with your side. My server (which is just a 5€/month 2-core server) takes ~70 seconds, having 200/1500 mb set in ES.

But as I have some plans for MVW requiring delta-updates, updates will be a matter of few seconds, if at all - whenever I implement it.

**Comment by bagbag** [comment]
I just did some basic tests with delta-updates.

Indexing of new filmlists will be done in like 0.5s, no need for "Server aktualisiert datenbank" anymore, as database will never be empty.

And my main goal with that: subscriptions!

**Comment by bagbag** [comment]
I just looked at the stats for ES running on Server:
`curl -XGET 'http://localhost:9200/_nodes/stats?pretty'`

Current RAM usage: 425MB

```
"mem" : {
  "heap_used_in_bytes" : 425200328,
  "heap_used_percent" : 27,
  "heap_committed_in_bytes" : 652529664,
  "heap_max_in_bytes" : 1555431424,
  "non_heap_used_in_bytes" : 124039160,
  "non_heap_committed_in_bytes" : 131780608,
  "pools" : {
	"young" : {
	  "used_in_bytes" : 56764608,
	  "max_in_bytes" : 139591680,
	  "peak_used_in_bytes" : 139591680,
	  "peak_max_in_bytes" : 139591680
	},
	"survivor" : {
	  "used_in_bytes" : 2611680,
	  "max_in_bytes" : 17432576,
	  "peak_used_in_bytes" : 17432576,
	  "peak_max_in_bytes" : 17432576
	},
	"old" : {
	  "used_in_bytes" : 365824040,
	  "max_in_bytes" : 1398407168,
	  "peak_used_in_bytes" : 432953088,
	  "peak_max_in_bytes" : 1398407168
	}
  }
}
```
