### ISSUE TITLE
[Beauty] Checkboxes and their texts are not neatly aligned. Improve alignment if possible.

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#48]
I noticed that text and box are *not* neatly aligned. Perhaps you can improve this so that the mid of the checkboxes is in the middle line of the texts (both vertically centered). Not important. Just my observation.

<img width="313" alt="bildschirmfoto 2017-02-12 um 18 38 46" src="https://cloud.githubusercontent.com/assets/1151915/22864494/d97391fe-f152-11e6-9afb-68339b2564b8.png">

Update: 
This is Firefox.

**Comment by bagbag** [comment]
I've spent some time doing that. Works fine on Chrome (even though they are not absolutely centered).

![unbenannt](https://cloud.githubusercontent.com/assets/4116942/22864654/d17aa598-f155-11e6-8944-f67125c0df91.png)

I'll take a look on it again with Firefox(?).

**Comment by Wikinaut** [comment]
Firefox (updated above).

**Comment by bagbag** [comment]
That's weird. It is aligned for me.
Firefox 51.0.1 on Arch

**Comment by 0880** [comment]
Firefox - Android Smartphone

![Screenshot](https://cloud.githubusercontent.com/assets/11850160/22949227/d06108ac-f301-11e6-8b5f-f0a013ae68de.png)

Firefox - Windows 10

![screenshot](https://cloud.githubusercontent.com/assets/11850160/22949626/2eaecf92-f303-11e6-82cb-6bf0b1caee84.png)

**Comment by bagbag** [comment]
@0880 Do you enabled any scaling or increased font-size in Firefox (because the text is bigger than the checkboxes)?

Firefox - Windows 10
![alignment](https://cloud.githubusercontent.com/assets/4116942/22949951/3802f806-f304-11e6-85e4-e84fb476b9bc.png)

Looks different for everyone 😅

**Comment by 0880** [comment]
Für den Screenshot (Windows 10) hab ich den Zoom verwendet. Spielt aber keine Rolle, da die Anordnung für mich absolut korrekt ist. Ich bin nicht der Meinung, daß daran etwas verändert werden müsste.

**Comment by bagbag** [comment]
Ich finde es zwar nicht korrekt so, aber unwichtig.

Wenn ich das Frontend neu schreibe (mache ich mit erscheinen von der ersten Bootstrap 4 **Beta**), achte ich darauf, dass das nicht wieder passiert.

@Wikinaut 
Von mir aus können wir auch Deutsch schreiben. Sind ja die einzigen hier. Und ein Internationales Projekt ist es auch nicht. Nur der Code und die Commits möchte ich definitiv weiter in Englisch.

**Comment by 0880** [comment]
>Ich finde es zwar nicht korrekt so, aber unwichtig.

Das es bei unterschiedlichen Usern jeweils anders aussieht? Mit Microsoft Edge ist es bei mir auch zentriert.

**Comment by bagbag** [comment]
Ja. Ich hätte es gerne so, dass es immer zentriert ist.

**Comment by 0880** [comment]
Bei der Vielzahl an verfügbaren Endgeräten wird es wohl immer Abweichungen bei der Darstellung geben.

Hier noch ein Beispiel:

![Screenshot](https://cloud.githubusercontent.com/assets/11850160/22964509/5644dea6-f359-11e6-89e9-e10a605ac8ee.png)

Die Beschreibung des Videos wird ausserhalb des Bildschirms angezeigt. Das Android Smartphone hat eine Auflösung von 1920x1080 Pixel.

**Comment by bagbag** [comment]
Mit dem neuen GUI wird es auch das nicht mehr geben, da die Beschreibungen dann anders dargestellt werden.

**Comment by Wikinaut** [comment]
Auf meinem debian 8 / Firefox ESR 45.7.0 (aktuell) ist der Effekt *nicht* vorhanden, alles ist perfekt ausgerichtet.

Ich habe das issue gemeldet, und schließe es jetzt.
