### ISSUE TITLE
Server issue: indexing appears to hang after a while

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#49]
After a while, the script, or elasticsearchor whatever, hangs.

Do you have an idea what is causing this ?

```
sudo systemctl status mediathekviewweb
● mediathekviewweb.service - MediathekViewWeb
   Loaded: loaded (/etc/systemd/system/mediathekviewweb.service; enabled; vendor
   Active: active (running) since Sun 2017-02-12 16:50:51 UTC; 6h ago
 Main PID: 17953 (node)
    Tasks: 10 (limit: 9830)
   CGroup: /system.slice/mediathekviewweb.service
           └─17953 node /srv/mediathekviewweb/app.js

Feb 12 22:52:06 cloud2 run.sh[17953]:         totalEntries: 164658
Feb 12 22:52:06 cloud2 run.sh[17953]:         entries: 129551
Feb 12 22:52:06 cloud2 run.sh[17953]:         done: false
Feb 12 22:52:06 cloud2 run.sh[17953]:         time: 1474.673 seconds
Feb 12 22:52:06 cloud2 run.sh[17953]:         pprogress: 100.00%
Feb 12 22:52:06 cloud2 run.sh[17953]:         iprogress: 78.68%
Feb 12 22:52:06 cloud2 run.sh[17953]:         totalEntries: 164658
Feb 12 22:52:06 cloud2 run.sh[17953]:         entries: 129551
Feb 12 22:52:06 cloud2 run.sh[17953]:         done: false
Feb 12 22:52:06 cloud2 run.sh[17953]:         time: 1475.173 seconds
```
 I stopped and restarted then elasticsearch and mediathekviewweb.

**Comment by bagbag** [comment]
It's running for months (huh, I can already say that) on the server and I never had that (or at least didn't saw that happening).

But I still wonder why it takes so long. Is your RAM full and ES is swapping on disk?

**Comment by Wikinaut** [comment]
May be. I also thought, that might be the reason. I will wait for your delta-index version, and close this issue now.

**Comment by bagbag** [comment]
As ES still need to be able to have the whole Filmliste indexed, that won't resolve that issue.

**Comment by Wikinaut** [comment]
Just a a question, perhaps you can try this on your Bastelserver:

When the web page is not accessed for a while (let's say, 12 hours or so, or more), indexing or connection hangs. Perhaps you can reproduce this. I am just interested in that.

Currently, it's useless on my tiny cloud server, because I had to restart every n hours. This is not a complain, and most likely caused by some effect, we cannot determine at the moment. But perhaps it's a small problem in the app code.

**Comment by bagbag** [comment]
Users accessing the page has no effect on indexing (which happens in a own process). The only connection they got is that both, searching and indexing using ES.

**Comment by bagbag** [comment]
I should start from scratch. The code is a mess and implementing delta-index (actually do any change) is stupid with that code. Same applies for Webinterface.

Thats because it's more or less my first JavaScript project.

**Comment by bagbag** [comment]
complete rewrite of indexing: done (91999deef118905d6302a87018dfee35393fb05c)

let's see if it still occours.

**Comment by Wikinaut** [comment]
nach kurzer Zeit kommt das http://dpaste.com/2TRW3E3.txt

**Comment by Wikinaut** [comment]
... und killt ES

**Comment by Wikinaut** [comment]
Meine Meinung weiterhin: Elasticsearch ist ein Biest, und sollte durch 'was Leichteres ersetzt werden.

**Comment by bagbag** [comment]
> { step: 'reCreateESIndex' }

Das ist die erste Reihe an "Befehlen", die ES bekommt. Und dabei handelt es sich um das Löschen und erneute erstellen des (leeren) Index. Das schaut für mich eher danach aus, als ob es erst gar nicht läuft und keine Verbindung bekommen.

**Comment by bagbag** [comment]
Habe jetzt mal testweise ES auf 500MB limitiert. Laut `curl -XGET 'http://localhost:9200/_nodes/stats?pretty'` wird davon gar nur 243MB genutzt.

Läuft ohne Probleme. Der Fehler liegt also wo anders.

**Comment by bagbag** [comment]
ES sollte durch zu wenig RAM auch nicht abstürzen, sondern aufgrund von Swapping einfach nur extrem langsam werden.

**Comment by Wikinaut** [comment]
Ich weiß auch nicht weiter. Probiere mal (bitte) den aktuellen Code in einem frischen "clone".

**Comment by bagbag** [comment]
Das habe ich während dem entwickeln mehrfach gemacht.

Was sagt denn `curl -XGET 'http://localhost:9200/_nodes/stats?pretty'`? Bzw gibt das was zurück oder auch nur "Keine Verbindung"?

**Comment by bagbag** [comment]
> und sollte durch 'was Leichteres ersetzt werden

Auch wenn ES nicht unbedingt ein Biest sein muss (aber durchaus sein kann), was wäre denn die Alternative?

Was mir einfällt:
PostgreSQL mit fulltext-search Kram,
oder wie am Anfang Redis.

**Comment by Wikinaut** [comment]
Ich benutze für so kleine Aufgaben "meine" fuzzy-search "agrep". https://github.com/Wikinaut/agrep

**Comment by bagbag** [comment]
Eine Text"durchsuchung"? Das wäre doch überhaupt nicht praktikabel aufgrund der Performance?
