### ISSUE TITLE
ARTE.FR vs. ARTE.DE "b-movie"

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#50]
Vielleicht ein Datenbank- oder Filmlistenproblem:

Eingabe von `b-movie` findet (derzeitig) nur den Eintrag bei ARTE.FR. Ich wollte den ARTE.DE haben.

**Comment by bagbag** [comment]
In der Filmliste ist es drin, liegt also an meinem Code.

![b-movie](https://cloud.githubusercontent.com/assets/4116942/23094685/f49fd58c-f5fd-11e6-9d6a-ab7ed2b85541.PNG)

**Comment by Wikinaut** [comment]
tja.... gut, dass ich das gemeldet habe. Der Film ist übrigens klasse.

**Comment by bagbag** [comment]
Auch nach einem kompletten neu indexieren ist es nicht enthalten, liegt also nicht am delta, soweit die gute nachricht 😄

**Comment by bagbag** [comment]
![fp](https://cloud.githubusercontent.com/assets/4116942/23095023/5be69c58-f603-11e6-8ad1-354293bcd4d4.jpg)


Ich mach da eine 3/4 Stunde lang rum und verstehe nicht wieso es nicht funktioniert.

Die Lösung: 
![losung](https://cloud.githubusercontent.com/assets/4116942/23094993/062ec3c6-f603-11e6-9044-1dcdaea33bd4.PNG)

**Comment by Wikinaut** [comment]
arrrrgh. Muss ich meine Donation aufstocken ?

**Comment by Wikinaut** [comment]
Aber: cool, dass Du es gefunden hast.

**Comment by Wikinaut** [comment]
Ähhhh, möglicherweise ein Grund, diese Box "Zukünftige" standardmäßig einzuschalten.

**Comment by bagbag** [comment]
Wenn du meine Zeit nochmal so verplemperst, dann werde ich über eine Aufstockung nachdenken 😃

Das ist ein guter Einwand. Ich denke ich mach es zumindest mal persistent.

**Comment by Wikinaut** [comment]
Ja, tut mir echt leid. Ich habe nur "Überall" probiert. Ach, beim Schreiben fällt mir ein: DAS ( = "Überall") sollte eventuell(!) "Zukünftig" beinhalten. Muss mal mal noch andere Leute fragen, ob das sinnvoll wäre.
