### ISSUE TITLE
Box not cleared on start

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#52]
Konsole:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create video.min.js:14:28836

**Comment by bagbag** [comment]
Siehe [https://github.com/videojs/video.js/issues/3325](https://github.com/videojs/video.js/issues/3325).

**Comment by Wikinaut** [comment]
(please reopen this issue)

#### How to reproduce

* start your Firefox browser
* start https://mediathekviewweb.de/
(works)
* press F5 to reload

#### Problem: Box not cleared, Website cannot be used any more

**Comment by bagbag** [comment]
Ich kann das nicht reproduzieren.

**Comment by fuller42** [comment]
have to reload the page 5-10x everytime to get the 'loading box' to disappear and make the site useable.
ff-esr-45.7

**Comment by Wikinaut** [comment]
@fuller42 @bagbag Yes, the problem is still present. Firefox ESR 45.9.0.

@fuller42 On my system, I have to close Firefox and restart the webside. A mere reload (F5, or even Ctrl F5 does not work here).

I suppose, it's a DOM rendering timing problem (race condition?) between different page parts, jQuery and Javascript.

**Comment by Wikinaut** [comment]
@fuller42 @bagbag Oh, Du hast doch recht: nach hartnäckigem Ctrl-F5 verschwindet die Box doch auch: 

"have to reload the page 5-10x everytime to get the 'loading box' to disappear and make the site useable." is correct.

**Comment by bagbag** [comment]
Give it a try now: 6936c2a2bd715bafea26f52ad207fd4346d67824

**Comment by Wikinaut** [comment]
@bagbag Ich habe den Sourcecode nicht mehr installiert... Hast Du diese Version online?

**Comment by Wikinaut** [comment]
Erster Versuch: ok!

**Comment by bagbag** [comment]
Ja, ist online.

**Comment by Wikinaut** [comment]
Erster Versuch: ok!

**Comment by Wikinaut** [comment]
Sieht so aus, als ob das Problem weg ist.
