### ISSUE TITLE
RSS-Feeds

### ISSUE THREAD

**Issue by bagbag** [mediathekview/mediathekviewweb#53]
RSS-Feeds als Vorläufer (und später Alternative) zu einem richtigen Abo-System.

**Comment by GitCoderix** [comment]
Excellent, really looking forward to this feature!

**Comment by bagbag** [comment]
Implemented: 006513ab934acf3879ebc29796caa8849e5cedbe

**Comment by Wikinaut** [comment]
Klasse. Kannst Du noch das title-Tag verändern, so dass es den Suchstring enthält ? Dann wird vermutlich der Feed-Name auch den Suchstring anzeigen.

Beispiel:
https://mediathekviewweb.de/feed?query=mord%20mit%20aussicht

Derzeit: 

Seitentitle = `MediathekViewWeb`

Vorschlag:

`MediathekVieWeb | Mord mit Aussicht` oder
`MVW | Mord mit Aussicht`

oder anstelle `|` einfach `-` als Trenner.

**Comment by Wikinaut** [comment]
(buche die Implementierung von meiner Spende ab ;-)

**Comment by bagbag** [comment]
Ich habe das jetzt in "description" drin.

Aber kann es auch gerne noch unter title machen.

**Comment by bagbag** [comment]
bitte: d5d92cc6294eb6b62a76073def4b027fb8f04098

**Comment by Wikinaut** [comment]
(Läuft gut).

Noch 'was: wenn ich auf einen der Feed-Einträge (feed items) klicke, erwarte ich eigentlich, auf der entsprechenden Webseite (beim Sender) zu landen, oder direkt bei der Video-Auswahl.

Ich glaube, dazu mache ich am besten ein neues Issue auf. (Tut mir leid, aber "Das Bessere ist der Feind des Guten.")

**Comment by bagbag** [comment]
Ja, daran habe ich auch schon gedacht, müsste dazu aber eine neue query implementieren (by id). Das habe ich auf später verschoben, um es jetzt so schon früher releasen zu können.

**Comment by Wikinaut** [comment]
ok. Ich mag das ("early release"). `Beauty comes later`
