### ISSUE TITLE
Popover: URL is drawn outside of screen

### ISSUE THREAD

**Issue by genodeftest** [mediathekview/mediathekviewweb#59]
Whenever I hover over the "movie" link in column "Video", a popover pops up showing a streaming and a download URL. Both URLs are rendered in a way that they reach beyond bounds of the popover.

![mediathekview-online-popover-issue](https://cloud.githubusercontent.com/assets/934401/23611836/34aee1fe-0279-11e7-87de-02f6e37b7884.png)

**Comment by bagbag** [comment]
I'm seeing this issue the first time now. Sorry.

Do you have any Privacy Addon installed? I am using Fonts and Icons from Google, so I guess you block them as they are not shown.

I will host them myself in the next version, which should fix that.

**Comment by genodeftest** [comment]
> Do you have any Privacy Addon installed? I am using Fonts and Icons from Google, so I guess you block them as they are not shown.

That was the reason for all the misbehavior. With a vanilla Firefox profile I see icons instead of the labels "movie", "ondemand_video" and "save".

So no bug at all. Sorry for the noise.
BTW: I would like if Mediathekviewweb was hosting all the fonts it uses.
