### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by paddsy** [mediathekview/mediathekviewweb#62]
Is it possible to watch with subtitles?
What do I do with a subtitle in xml format ? 
How can I convert xml to srt ?

**Comment by bagbag** [comment]
Unfortunately neither native video tag, nor video.js (what I use) have support for xml subtitle.

By using Google I found [http://www.nikse.dk/subtitleedit/](Subtitle Edit), but I didn't tested it.

**Comment by paddsy** [comment]
Subtitle Edit does not work on mac. I found this one:
 https://gotranscript.com/subtitle-converter
 and it seems to work.
