### ISSUE TITLE
ERR wrong number of arguments for 'spop' command

### ISSUE THREAD

**Issue by toblinga** [mediathekview/mediathekviewweb#63]
Hi, I have installed today the latest version on Ubuntu 16.04 followed your installation guide. But when I start the software with `node app.js` the "filmliste" will be downloaded end parsed but at the end the following exception will be thrown a few times.

> Error: ERR wrong number of arguments for 'spop' command
>     at IPC.ipc.on (/srv/mediathekviewweb/MediathekIndexer.js:276:26)
>     at emitOne (events.js:96:13)
>     at IPC.emit (events.js:191:7)
>     at ChildProcess.IPC.proc.on (/srv/mediathekviewweb/IPC.js:9:18)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at process.nextTick (internal/child_process.js:766:12)
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

The web UI works, but the table does not show any entry.

Please, could you help me.

Thx.

**Comment by bagbag** [comment]
Which version of redis are you running?

**Comment by toblinga** [comment]
redis-server --version gives following information:

Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64
build=687a2a319020fa42


2017-03-11 8:05 GMT+01:00 Patrick <notifications@github.com>:
