### ISSUE TITLE
Componentize FilmlistenParser -> Elasticsearch

### ISSUE THREAD

**Issue by jankal** [mediathekview/mediathekviewweb#64]
As far as I know from brief scroling through the code, @bagbag you are parsing the Filmliste to an Elasticsearch server.

If it's possible I'd like to get this out of mediathekvieweb and create a new repo for it so one can just parse the Filmliste without having whole mediathekviewweb.

@alex1702 What do you think about this?

-------
Für @alex1702 auf Deutsch:
Soweit ich jetzt beim durchscrollen gesehen habe, parst @bagbag die Filmliste in einen Elasticsearch-Server.

Möglicherweise könnten wir das in eine eigene Komponente auslagern, sodass Nutzer ohne das gesamte mediathekvieweb-Repo zu brauchen, die Filmliste parsen und in Elasticsearch speisen können.

Dies wäre ein neuer Startpunkt für mediathekview/FLAPI

@alex1702 Was meinst du dazu?

**Comment by jankal** [comment]
@alex1702 With the mediathekviewweb Elasticsearch srver existing, this means there also right now actually is an API for the Filmliste (don't know if it's public)

**Comment by bagbag** [comment]
Ich habe mit Alex schonmal darüber gesprochen (da ihr sowas ja bereits vor hattet).

Die ES-Instanz ist logischerweise nicht öffentlich (sonst könnte man ja alles mögliche damit anstellen), aber es gibt eine (noch nicht dokumentierte API): [gist.github.com](https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de)

**Comment by jankal** [comment]
@bagbag Wie effizient ist die aktuelle parsing-Implementation für die Filmliste?

**Comment by bagbag** [comment]
Was verstehst du unter effizient? Das parsen dauert keine 10 Sekunden, das erste indizieren 30 Sekunden oder so und die folgenden - delta-updates sei dank - 1-2 Sekunden.

Es wird zuerst nach Redis geparst (und ein klein wenig verändert, z.B. die richtigen URLs generiert), dort dann mit den (extrem extrem schnellen) Operatoren ein delta-update erzeugt, und zuletzt von dort mit mehreren parallelen Instanzen in Elasticsearch eingespeist.

**Comment by jankal** [comment]
@bagbag Das ist mal überaus schnell. Ich bin grad dabei, eben einen solchen parser zu bauen, der in MariaDB speist. (Ich gehe davon aus, dass dieser einige Minuten sicher brauchen wird.) Allein wegen MariaDB wird das nie so schnell werden.

Welche Operatoren nutzt du für das Delta update? - Normal müsste dafür doch die komplette vorhandene Datenbank gelesen werden, um solche Deltas zu erzeugen. Wie funktioniert das so schnell? - Magie?

@alex1702 Ich meine, alleine wegen des Zeitaufwands sollte möglicherweise doch ES genutzt werden.

**Comment by bagbag** [comment]
[SDIFF](https://redis.io/commands/sdiff).

Redis braucht, um 2 Listen mit knapp 200.000 Einträgen zu vergleich einen Bruchteil einer Sekunde.

**Comment by alex1702** [comment]
also ich hatte es vor die komplette filmliste in redis vor zu halten und zu bearbeiten und diese ansonsten dann in eine Datenbank wie mariadb oder mongodb für die feste Lagerung vor zu halten. und das ganze halt in go schreiben.

**Comment by bagbag** [comment]
Das ist unnötig. Redis kann auch alle Daten auf die HDD speichern, sodass bei einem Neustart wieder alles da ist.

Wieso überhaupt etwas eigenes machen? Das was ich gebaut habe sollte doch absolut ausreichend, wenn nicht gar optimal sein?

**Comment by jankal** [comment]
@bagbag Das ist der Grund für dieses Issue. Und ich selbst erkenne das auch. Ich bin mit jeder anderen Implementation mindestens doppelt so langsam. Egal ob in PHP oder Go.

**Comment by jankal** [comment]
Falls es jemanden interessiert: [mediathekview/filmliste-mysql](//github.com/mediathekview/filmliste-mysql)

Parser: [mediathekview/filmlisten-parser](//github.com/mediathekview/filmlisten-parser)

Der PHP-Code fürs direkte speichern in MariaDB würde so aussehen. Ich hab aktuell aber keinen blassen schimmer, wie wir da ordentliche Updates hinbekommen (da wäre Redis wieder...)

**Comment by bagbag** [comment]
PHP, kein Wunder 😃

Also von mir aus kann ich da gerne Anpassungen machen, die für MV nötig sind.

**Comment by jankal** [comment]
@bagbag Liegt vermutlich nicht nur an PHP sondern auch an MariaDB, dass wir damit niemals diese Geschwindigkeiten hinbekommen werden. @alex1702  Ich bin auch bei Go skeptisch, ob es tatsächlich schneller ist (Multithreading für Filmlisten wäre vermutlich nicht so gaaanz einfach...)

**Comment by bagbag** [comment]
Warum sollte Multithreading da schwierig sein?

Aber beim Parsen ist es auch gar nicht nötig, da schnell genug.

**Comment by jankal** [comment]
@bagbag Also nun ich werde meinen Parser mal testen, ohne es irgendwo hin zu schreiben.

Dann werde ich sehen, wie langsam es ist.

**Comment by bagbag** [comment]
Hier mal das Parsing und Indexing von MVW: [https://batrick.de/mvw-parsing-indexing.mp4](https://batrick.de/mvw-parsing-indexing.mp4)

Zuerst Delta-Parsing mit einer Filmliste, die >1 Woche alt (also ein ziemlich großes Delta).
Und nach dem "redis-cli flushall" ein komplettes neu Parsing.

**Comment by jankal** [comment]
Wow!

Mein Parsing-Test ist ziemlich negativ ausgegangen. Nach einiger Zeit hat es mit einem Segmentation Fault aufgehört. Macht auch aktuell nur circa 10 Sendungen/s.

**Comment by bagbag** [comment]
Das ist enorm 😄 Da kann ja dann irgendwas nicht stimmen.

**Comment by jankal** [comment]
Naja... er hat beim 13322. Film den Segfault geworfen...

**Comment by jankal** [comment]
@bagbag Auf jeden Fall schonmal danke fürs ausgliedern dieser Komponente dann.

**Comment by bagbag** [comment]
Warum denn ausgliedern?

Es kann doch sowohl MVW als auch MV auf die API zugreifen. Und im Prinzip ist das ganze ja schon alleine, es müsste nur der "Webclient-ausliefern-Part" weg.

**Comment by jankal** [comment]
Ja meine idee war, das in ein eigenes Repo zu scheiben, und dann in MVW über NPM oder ähnliches zu laden.

Wies nicht, inwieweit das möglich ist.

**Comment by jankal** [comment]
@alex1702 @bagbag 
Meine Implementation braucht aktuell vermutlich in Richtug 1 min.

Wäre also vermutlich noch im Rahmen.

Der Segfault und das RAM-Problem kamen von Xdebug.

**Comment by bagbag** [comment]
Ich verstehe immer noch nicht wieso was neues, aber gut.

**Comment by jankal** [comment]
@bagbag Weil angefangen. Ich hatte keinen blassen Schimmer, dass deine Implementation in NodeJS schon existiert.

**Comment by jankal** [comment]
So. Ich habe meine Repos nun gelöscht, da sich hier so wies aussieht keiner eine Nutzung vorstellen kann.
@alex1702 Bitte entferne auch mediathekview/FLAPI. Du willst es ja eh in Go.

So ich beuge mich eurem Willen in Richtung NodeJs und Go jetzt, obwohl ich sehe, dass schon ein Haufen Arbeit geleistet wurde.

Bessere Kommunikation vin @alex1702's Seite hätte das möglicherweise verhindern können (ich wusste bis gestern nichts von dem genialen Parser von @bagbag)

Desweiteren werde ich alle weiteren Arbeiten an MediathekView oder MediathekViewWeb nichtmehr mitgehen. Außerdem schalte ich den Filmlisten-Mirror mit sofortiger Wirkung mediathekview.jankal.me ab.
