### ISSUE TITLE
Enhancing search with duration constraints

### ISSUE THREAD

**Issue by schnesim** [mediathekview/mediathekviewweb#66]
It would be great to have a feature where you can set a min and max duration for the search results.

Like "!3sat min=>20 max<=40" to get all 3sat entries which last between 20 and 40 minutes.

**Comment by bagbag** [comment]
At the moment I am completely recoding the client and server. Whenever this is done, you will be able to filter by duration and many more properties.

**Comment by c64bob** [comment]
Is there an approximate ETA for when this will be done? 
Thanks for this great software!

**Comment by theelectricsoul** [comment]
Without a duration filter, the other filters do not make much sense. There are hundrets of 2-3 minutes videos within the search results. This makes it hard to filter for whole documentaries.

Please hurry ;)   thanks a lot for your website

**Comment by bagbag** [comment]
Implement with #159, thanks to @marcusfey!
