### ISSUE TITLE
Datatables warning

### ISSUE THREAD

**Issue by japeberg** [mediathekview/mediathekviewweb#69]
> DataTables warning: table id=mediathek - Requested unknown parameter 'topic' for row 11, column 1. For more information about this error, please see http://datatables.net/tn/4

This error messages appears when I try to enter 'arte de' into the search mask. The query works fine, but the error message still appears.

**Comment by bagbag** [comment]
As MVW 2.0 should be ready to be released soon (at least as beta), I just did it dirty by disabling the warning: 6d97e2240e560221dcedcf3fc2211cf9c96def3a
