### ISSUE TITLE
Nicht alle verfügbare downloadsstelles erscheinen in Mediathekview

### ISSUE THREAD

**Issue by FreekTtort** [mediathekview/mediathekviewweb#70]
Hallo Freunden,

Ich bin aus die Niederlande und guck gerne Tatort um mein Deutsch zu verbessern (jetzt aber noch scheisse, enschüldigung!)

Die meiste Folgen kann ich ohne Problemen mit MediathekView downloaden, aber manchmal, selten, gibt es ein Geoblocking error (vielleicht ein Fehler des ARD, wir können allen ARD auf das Fernsehen anschauen und sollten das auch auf internet können), zum beispiel die Folge "Ein Fuß kommt selten allein". Und das stimmt, wann ich zu die url gehe:
http://www.ardmediathek.de/tv/Tatort/Tatort-Ein-Fu%C3%9F-kommt-selten-allein/WDR-Fernsehen/Video?bcastId=30556746&documentId=42164548
gibt das auch ein geoblocking error. So das ist ARD's Problem, kein Fehler des mediathekview!

Aber ich habe jetzt herausgefunden das wann ich zum website des ARDs gehe, ich da die Folge kann anschauen ohne geoblocking!
http://www.daserste.de/unterhaltung/krimi/tatort/videos/ein-fuss-kommt-selten-allein-102.html
aber das erscheint nicht in Mediathekview, und ich kann es deswegen nicht herunterladen!

Vielleicht können sie auch die sendungen auf daserste website zum mediathekview hinzufügen?

**Comment by bagbag** [comment]
Hierfür ist MediathekViewWeb der falsche "Ansprechpartner", aber ich gebe es weiter. Ich danke dir für den Hinweis :)

**Comment by Nicklas2751** [comment]
@FreekTtort Aber ich kann dir Helfen. Dein erster Link ist die Tatort Folge "Ein Fuß kommt selten alleine" wie sie vom **WDR** ausgestrahlt wurde und der zweite Link ist sie wie sie von der **ARD/Das Erste** ausgestrahlt wurde. Inhaltlich wird das keinen Unterschiedmachen aber das WDR macht hier vermutlich anderes Geo Blocking als die ARD.

Die Folge ist in MediathekView(Web) sowohl für ARD als auch für WDR gelistet: https://mediathekviewweb.de/#query=Ein%20Fu%C3%9F%20kommt%20selten%20allein

P.s. In Zukunft Fehlende Sendungen im [Forum](https://forum.mediathekview.de/) melden. Siehe hierzu; [Anleitung - Fehlende Sendung melden](https://forum.mediathekview.de/topic/99/fehlende-sendung-melden)

**Comment by FreekTtort** [comment]
Danke Nicklas2751, aber das stimmt nicht. Ich benutze die offline-version und das gibt er zwei eingaben für die Folge
ARD:
http://www.ardmediathek.de/tv/Tatort/Tatort-Ein-Fu%C3%9F-kommt-selten-allein/WDR-Fernsehen/Video?bcastId=30556746&documentId=42164548
und WRD:
http://www1.wdr.de/mediathek/video/sendungen/tatort/video-tatort---ein-fuss-kommt-selten-allein-100.html
und beide fehlschlagen infolge geoblocking, und ich habe die links auf die online-version auch versucht und die funktionieren auch nicht.

aber die version auf die daserste.de site wirkt! und habe ich jetzt auch heruntergeladen nach viel suchen ins source-code  
http://www.daserste.de/unterhaltung/krimi/tatort/videos/ein-fuss-kommt-selten-allein-102.html

und die erscheint nicht in mediathekview, aber es sollte!

**Comment by pidoubleyou** [comment]
Es wird aktuell nur die ARD-Mediathek sowie die der dritten Programme (BR, WDR usw) durchsucht, die von Das Erste nicht.
Deshalb erscheint auch der funktionierende Link nicht in MV. Anscheinend hat die Mediathek von Das Erste andere Geo-Blocking und auch Jugendschutz Einstellungen, als die anderen, weshalb der Download funktionierte.

**Comment by FreekTtort** [comment]
Ja das verstehe ich aber das ist das Problem! Weil die Das Erste Mediathek nicht durchsucht würde können wir die Folge nicht herunterladen trotzdem die für uns verfügbar sind auf Das Erste Mediathek. Lösung: auch Das Erste mediathek durchsuchen!

**Comment by bagbag** [comment]
Da das nicht zu MVW sondern MLib gehört und es bereits bekannt ist, schließe ich das jetzt.
