### ISSUE TITLE
 [Bug] Beim Abspielen/Download wird der Filename statt des Filmtitels angezeigt/genommen

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#71]
Siehe auch https://github.com/YggdrasiI/plugin.video.simple_mediathek_de/issues/4 (für das Kodi Plugin).

Beim Herunterladen von (Beispiel Adenauer-Doku) http://pd-videos.daserste.de/int/2017/04/12/bfd367a5-bb2d-49fb-b767-77be44768f3a/512-1.mp4

wird als Filename beim Schreiben leider nur `512-1.mp4` genommen.

Schöner wäre es, wenn der Filmname `Konrad Adenauer - Stunden der Entscheidung`, Thema `Reportage & Dokumentation` und evtl. das Datum, also die Metadaten, als Dateinamen genommen würden.

**Comment by bagbag** [comment]
Es ist leider nicht möglich, siehe hierzu #19.
