### ISSUE TITLE
Teilweise fehlende Daten (möglicherweise ein Filmlistenproblem)

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#72]
siehe

![20170425-22 04 27_auswahl](https://cloud.githubusercontent.com/assets/1151915/25405311/3694ec00-2a03-11e7-8fe3-d9d709288283.png)

Die Suchmaschine brauchte 11,15 ms. Zeige Treffer 1 bis 15 von insgesamt 177077 Treffern.
Filmliste zuletzt um 21:22 Uhr aktualisiert. (25.04.2017)

**Comment by bagbag** [comment]
Das ist nicht zum ersten Mal so. Zumindest beim letzten Mal war da die Filmliste leer, ich schätze das ist es dieses mal auch.

**Comment by Wikinaut** [comment]
ok
