### ISSUE TITLE
Mixed Content Probleme [SRF]

### ISSUE THREAD

**Issue by 0880** [mediathekview/mediathekviewweb#73]
Das Abspielen einiger Videos mit dem HTML5 Video Player funktioniert nicht mehr. Statt HTTP müsste wieder auf HTTPS umgestellt werden.

>Mixed Content: The page at 'https://mediathekviewweb.de/#query=!SRF' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://hdvodsrforigin-f.akamaihd.net/i/vod/sportaktuell/2017/04/sportaktuell_20170425_224807_5240403_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index_5_av.m3u8'. This request has been blocked; the content must be served over HTTPS.

**Comment by bagbag** [comment]
Es ist ne neue Domain, die nun mit drin ist: b150f5c14107e38085a8e0098e31ad0b6243392b
