### ISSUE TITLE
Rss Feed for Podcatcher

### ISSUE THREAD

**Issue by marcus-at-localhorst** [mediathekview/mediathekviewweb#75]
Would be awesome to subscribe to shows via Over Cast or similar.
Thanks!

**Comment by bagbag** [comment]
I've put it on the Milestone for MVW 2.0: https://github.com/mediathekview/mediathekviewweb/issues/67

**Comment by fungs** [comment]
I've come here to suggest the same: make the text RSS feeds actual video feeds so one can subscribe to any search with an RSS program (like antennapod on Android) and stream directly from this program. This modification should be straight-forward.

Possible complications:

1. pick a suitable video quality level when subscribing: this requires some way to suggest a resolution range, bit rate or similar which is applicable to all streams)
2. specification of the stream format: don' t know if you have to specify the encoding in an rss feed and if this is already in the metadata

Keep up the good work. Thanks!
*

**Comment by mahibi** [comment]
I also use antennapod on Android and I figured out that i can subscribe to MVW-searches by tranforming the Link. I have to replace "#query=" with "feed?query=".
Example:

`https://mediathekviewweb.de/#query=pierre%20M.%20krause`   (doesn't work)
to
`https://mediathekviewweb.de/feed?query=pierre%20M.%20krause`   (works fine)

With this i can't really get the media-content itself into antennapod (so it's not an actual video feed as  @fungs already mentioned) but the podcasts are added with the Name "MVW - [name]" and i see the descriptions for the episodes. RSS-updating of the episode descriptions works fine. I can't stream or download the content directly, but antennapod offers a link to visit the Website, which opens the video in your web browser. So this is already really great!

Are there any efforts to support video feeds so streaming and downloading would be possible in podcatchers?

**Comment by fungs** [comment]
Which video quality did you select for the feed? Watching on your phone and/or streaming via mobile networks you probably don't want the super-high resolution but on my computer/tablet I do want it.

**Comment by bagbag** [comment]
It's the highest available.

**Comment by Art4** [comment]
I have the same problem like @fungs describes. What about an optional GET parameter `&quality=low|normal|high` to define the quality?

**Comment by fungs** [comment]
@Art4 see the new issue #132 and comment there please

**Comment by Art4** [comment]
#132 has a milestone for v2, but I aimed to fix this in v1. But I will comment there, thanks. :+1:

**Comment by bagbag** [comment]
I don't think I will fix this for v1, at least not fully fledged, as this would require changes at the UI too and I just don't feel like doing stuff at v1 anymore.

Pull request welcomed.
