### ISSUE TITLE
Error on Playback

### ISSUE THREAD

**Issue by nitsnatsnok** [mediathekview/mediathekviewweb#76]
When I try to view a video (no matter which!), the player only shows the message “The media could not be loaded, either because the server or network failed or because the format is not supported.” – how can I fix this? I'm running Chromium 58.0.3029.110 on Ubuntu 16.04 64-bit.

**Comment by bagbag** [comment]
Is there any output in developer-console (F12)?

**Comment by nitsnatsnok** [comment]
Indeed there is:

    video.min.js:18 VIDEOJS: Cast APIs not available
    video.min.js:18 VIDEOJS: Cast APIs not available. Max reconnect attempt
    mediathekviewweb.de/:1 Mixed Content: The page at 'https://mediathekviewweb.de/' was loaded over HTTPS, but requested an insecure video 'http://avdlswr-a.akamaihd.net/swr/swr-fernsehen/landesschau-rp/gut-zu-wissen/2017/05/941007.sm.mp4'. This content should also be served over HTTPS.
    video.min.js:18 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. d {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

The first two lines appear over and over again in the console, the other two just once. Chromium seems to rate the video as insecure, so maybe standard security settings stand in the way here?

**Comment by nitsnatsnok** [comment]
Find further information regarding this [here on developers.google.com](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content).

**Comment by bagbag** [comment]
That Mixed Content is fine. There's no other way, as some Mediatheks are only serving over that.

To be honest, if have absolutely no clue.

**Comment by nitsnatsnok** [comment]
Works fine with Firefox 53.0.3 (64-Bit), what could be wrong with Chromium? …

**Comment by bagbag** [comment]
I don't know. It works flawless with Chromium on ArchLinux for me.

**Comment by nitsnatsnok** [comment]
That's just strange – thanks for your patience though!

**Comment by bagbag** [comment]
Can you play it in a new tab?

**Comment by nitsnatsnok** [comment]
No, the player gets grayed out after a second.

**Comment by bagbag** [comment]
So it's definitely unrelated to MVW and therefore I can close it.
