### ISSUE TITLE
Feature Request: Filter results by stream size

### ISSUE THREAD

**Issue by sfxxx** [mediathekview/mediathekviewweb#77]
Hi, I love your project. It'd be very nice if one could filter or sort the available streams by size, so that all the small trailers and such don't dilute the results list if you're looking for a longer movie to watch. Sorry if this is a duplicate or if I miss anyting, I tried to find a way but couldn't.

**Comment by bagbag** [comment]
You're right, it's not possible yet.

At the moment I'm developing MVW 2.0 (completely from scratch) and if I can keep my current speed it **could** be done next weekend. Then you will be able to filter short videos.

**Comment by sfxxx** [comment]
Thanks for your reply. Sounds great. Good luck with the rewrite!

**Comment by bagbag** [comment]
Despite the fact that next weekend is long ago :D, I don't have the filesizes at query time (it's fetched on demand when someone hovers over an entry), so it's not possible, at least not with the current data I get.

But you will be able to filter by duration in any of the future weekends.

**Comment by sfxxx** [comment]
I appreciate your feedback nonetheless. Thanks.
