### ISSUE TITLE
Is it possible to show media from funk.net?

### ISSUE THREAD

**Issue by maciboy** [mediathekview/mediathekviewweb#79]
Hi!
First of all a huge thanks for this awesome tool!

I’m wondering if it would be possible to add files from ARD’s channel funk.net to the library, e.g. to easily stream „The IT Crowd“ ;)
https://www.funk.net/serien

Would be great!
Thanks again!

**Comment by bagbag** [comment]
I've started a thread about it in the forum: [https://forum.mediathekview.de/topic/522/funk-net-von-ard-zdf-mit-in-die-filmliste-aufnehmen](https://forum.mediathekview.de/topic/522/funk-net-von-ard-zdf-mit-in-die-filmliste-aufnehmen).
