### ISSUE TITLE
Query-API broken

### ISSUE THREAD

**Issue by cemrich** [mediathekview/mediathekviewweb#80]
The webapp does expose an API for getting all channels and querying for shows. However, a post to https://mediathekviewweb.de/api/query returns an error right now: ```Unexpected token o in JSON at position 1```

This might be an error in ```app.js``` where an object (req.body) is treated as json string (see https://stackoverflow.com/questions/8081701/i-keep-getting-uncaught-syntaxerror-unexpected-token-o). Simply removing the call to ```JSON.parse``` should do the trick.

**Comment by bagbag** [comment]
Take a look at https://gist.github.com/bagbag/a2888478d27de0e989cf777f81fb33de

**Comment by cemrich** [comment]
Thank you very much for your quick response! I missed a header using curl: You have to set the content type explicitly to 'text/plain' for the server to respond correctly.

For future reference - a curl request could look like:

    curl 'https://mediathekviewweb.de/api/query' -H 'content-type: text/plain' --data '{"queries":[{"fields":["title","topic"],"query":"sturm der liebe"},{"fields":["channel"],"query":"ndr"}],"sortBy":"timestamp","sortOrder":"desc","future":false,"offset":0,"size":10}'
