### ISSUE TITLE
Feature request: Expose and filter by language

### ISSUE THREAD

**Issue by cemrich** [mediathekview/mediathekviewweb#82]
At the moment the mediathek list contains German and French entries. It would be great to be able to filter by language or exclude entries with a specific language.

**Comment by bagbag** [comment]
Unfortunately the Filmliste doesn't contain any information about the language. Isn't arte.fr the only channel with french stuff? So you could filter by channel.

**Comment by cemrich** [comment]
Yes, I would like to do this. Is there a possibility to exclude a single channel without listing all other channels available?

**Comment by bagbag** [comment]
Unfortunately not. It will be with MVW 2.0. But I guess that this helps you: [API for list of channels](https://mediathekviewweb.de/api/channels)

**Comment by cemrich** [comment]
Thank you! To avoid errors I'll wait for 2.0.
