### ISSUE TITLE
Symbols shown as text Problem in Firefox 56.0 (64bit) 

### ISSUE THREAD

**Issue by gw-issues** [mediathekview/mediathekviewweb#84]
The symbols in the columns description (expand_more) and video "Movie" as well as in the headers of column Description and Video and the clear symbol in the search filed are shown as the corresponding text, not as symbol (see attached screendump). This is present only in Firefox 56.0, not in IE or Google Chrome. Possible reason for issue: maybe a resourcefile is reference relative and not absolute.

Problem was tested on 14.10.2017 8:32.

![grafik](https://user-images.githubusercontent.com/32788545/31573365-638ad556-b0ba-11e7-9d88-3fe9533fe564.png)

**Comment by bagbag** [comment]
This happens when an ad blocker or similar is blocking Google, because the icons are served by Google.

**Comment by hajika** [comment]
could you provide a solution that works without google? I'am blocking it and I don't want to unblock it and be tracked by google. So the popup looks like this:

![screenshot_2018-01-26_19-47-44](https://user-images.githubusercontent.com/27491258/35455366-e8285860-02d1-11e8-824c-f18a7c25199f.png)

ok one could say, just unblock google, but I hope there is a privacy friendly solution.

**Comment by hajika** [comment]
I guess this issue can be closed as well, because the icons are selfhosted now: https://github.com/mediathekview/mediathekviewweb/issues/95

**Comment by bagbag** [comment]
You're right.
