### ISSUE TITLE
(Development branch) Can't start client

### ISSUE THREAD

**Issue by YggdrasiI** [mediathekview/mediathekviewweb#86]
Hallo Bagbag, 

leider ist es mir nicht gelungen den Client in der Development-Version (Commit f6515b5) zu starten. Vor `ng serve` oder `ng build` habe ich mittels `npm install` lokal die Abhängigkeiten aufgelöst.

Ob es nun am Code dieses Projektes liegt oder an den, zumindest obersten Ebene, neueren Paket-Versionen, kann ich nicht erkennen.

MfG YggdrasiI

```>node --version
v8.8.1
>npm  --version
5.4.2
>Angular-cli-Version: 1.4.5
>Webpack-Version: 3.8.1
```

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-10-30T11:50:11.611Z                                                        
Hash: 9cd711b56810e777bf3a
Time: 8873ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.06 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 323 bytes {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 192 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 338 kB [initial] [rendered]

ERROR in /home/user/software/mediathekviewweb/common/src/model/entry.ts (27,18): Type '"media.quality"' is not assignable to type 'Field'.
ERROR in /home/user/software/mediathekviewweb/common/src/model/entry.ts (16,8): Type '"id"' is not assignable to type 'Field'.
ERROR in /home/user/software/mediathekviewweb/common/src/model/entry.ts (18,11): Type '"topic"' is not assignable to type 'Field'.
[...]
ERROR in /home/user/software/mediathekviewweb/client/src/app/components/entry-table/entry-row-overview/entry-row-overview.component.ts (3,10): Module '"/home/user/software/mediathekviewweb/client/src/app/common/model/index"' has no exported member 'IEntry'.
ERROR in /home/user/software/mediathekviewweb/client/src/app/components/entry-table/entry-row-detail/entry-row-detail.component.ts (3,10): Module '"/home/user/software/mediathekviewweb/client/src/app/common/model/index"' has no exported member 'IEntry'.

webpack: Failed to compile.
```

**Comment by bagbag** [comment]
Ja, der development-Branch ist momentan noch nicht wirklich zum testen geeignet, da es es paar Baustellen gibt. Außerdem ist das query-parsing (daran bist du interessiert?) noch nicht im Client implementiert und kann daher nicht wirklich viel.

Wenn du willst, kann ich jetzt gezielt den Client lauffähig machen (zumindest mit dem, was momentan implementiert ist), wobei ich nicht wüsste was du davon hättest. Zumal der Client alleine sowieso nicht viel bringt und der Server lässt sich auch (noch) nicht einfach so starten, da er aus mehreren voneinander unabhängigen Teilen besteht (naja, indirekt sind sie natürlich schon voneinander abhängig) und ich noch kein "zentralen Starter" implementiert habe.

Falls es dir nur ums query-parsing geht (?), so kannst du in Zukunft dann entweder einfach ein query-string an die API schicken oder alternativ zeige ich dir den Weg im Code zu den relevanten Stellen.

**Comment by YggdrasiI** [comment]
Hallo Babag,

den Client gezielt nur für mich in lauffähig zu machen, wirklich zu viel Arbeit. Ich ging davon aus, dass es in so einem Zustand ist.

Ja, der Hintergrund der Frage war die Konstruktion der Querys. Aus der abstrakten Definition, welche du verlinkt hattest, konnte ich leider nicht erkennen, wie eine Abfrage am Ende strukturiert ist, und an welches Ziel sie ginge.
Außerdem kenne ich Angular, sofern das überhaupt die Komponente ist, über die ich mich informieren müsste, nicht. Daher wollte ich mir die Requests anschauen, die der Client sendet.
Wenn du mir ein Beispiel-Request geben kannst, würde mir das aber fast genauso gut helfen :)

Ist ein Server mit der neuen API schon erreichbar? Der zweite Grund meiner Frage war, dass ich die Verwendung der API ja auch testen müsste.

Sofern diese beiden Dinge (Beispiel-Request erzeugbar, Public Server verfügbar) für dich mit Aufwand verbunden sind, würde ich vorschlagen die Sache zu vertagen. Nach dem Release von MVW 2.0 sollte die Sache wesentlich leichter sein und unnötige Arbeit vermieden worden sein.

**Comment by bagbag** [comment]
Naja, die Arbeit wird so oder so kommen 😄 Der Client ist auch schon in dem Zustand abfragen abzusenden und die Antwort anzuzeigen, aber die Texteingabe wird eben noch nicht geparst, sondern nur ne fixe Abfrage gemacht. Die Anfragen sendet der Client an den Server, der den Client ausgeliefert hat, da ist kein fixer Endpoint angegeben. Am ende hätte dir der Client also gar nichts genützt.

Die [Definition](https://github.com/mediathekview/mediathekviewweb/blob/development/common/src/search-engine/query/definition.ts) ist im Prinzip alles was du brauchst, ich hätte aber wohl noch dazu sagen müssen wie du es interpretieren kannst (ich gehe davon aus, dass du mit JSON umgehen kannst).

Das Root-Element der Query ist
```
type QueryObject = {
  body: Query;
  sorts?: Sort[];
  skip?: number;
  limit?: number;
}
```

Der Parameter body ist vom Typ Query, was eine Query sein kann, sieht man in der Definition: `type Query = IDsQuery | MatchAllQuery | BoolQuery | RangeQuery | TextQuery | RegexQuery`.

Nehmen wir uns mal die TextQuery raus:
```
TextQuery = {
  text: {
    fields: string[];
    text: string;
    operator: 'and' | 'or';
  }
}
```
füllen diese aus
```
{
  text: {
    fields: ["channel"],
    text: "Tagesschau",
    operator: "and"
  }
}
```
und packen es in das Root-Element. sorts, skip und limit ist Optional (anhand des ? zu sehen), also lassen wir das mal weg.
```
{
  body: {
     text: {
       fields: ["title"],
       text: "Tagesschau",
       operator: "and"
     }
   }
}
```

Fertig wäre eine sehr simple Query, die den Titel nach "Tagesschau" durchsucht. Da wir aber in der Regel nach mehr als nur dem Titel durchsuchen wollen, es zudem sortiert brauchen und keine 15.000 Ergebnisse wollen, nehmen wir eine BoolQuery (die, wie in der Definition zu sehen, beliebig viele unter-Queries haben kann), packen da unsere Kriterien rein und geben die optionalen Parameter an:
```
{
  body: {
    bool: {
      must: [{
          text: {
            fields: ["channel"],
            text: "ARD",
            operator: 'and'
          }
        },
        {
          text: {
            fields: ["title"],
            text: "Tagesschau Gebärdensprache",
            operator: 'and'
          },
        }
      ],
      not: [{
        text: {
          fields: ["topic"],
          text: "tagesschau24",
          operator: 'and'
        }
      }],
      filter: [{
        range: {
          field: "timestamp",
          lte: "now+1h/m",
          gte: 1509464430
        }
      }]
    }
  },
  sorts: [{
    field: "timestamp",
    order: "descending"
  }, {
    field: "duration",
    order: "ascending"
  }],
  skip: 0,
  limit: 25;
}
```


Die möglichen Felder findest du im [Model](https://github.com/mediathekview/mediathekviewweb/blob/c3d495de7f621add985bc03942b081a90aa768dc/common/src/model/entry.ts#L15), wobei da in Zukunft zumindest noch "time" zusätzlich zum kombinierten "timestamp" hinzu kommen wird, um unabhängig vom Datum zu filtern.

Vielleicht ist dir aufgefallen, dass die BoolQuery sowohl "must" als auch "filter" hat, was im Endeffekt das gleiche bewirkt, aber irgendwann einmal nützlich ist, um die Scoring-Funktion von Elasticsearch (und vielen anderen beeinflussen zu können). Ebenfalls könnte dir aufgefallen sein, das im Range-Filter einmal eine Zahl und einmal ein String angegeben ist, siehe hierzu [Date Math von Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math).

Ich habe mir für den Kram [Query-Builder](https://github.com/mediathekview/mediathekviewweb/tree/development/common/src/search-engine/query/builder) gebaut, um nur noch sowas machen zu müssen:
```
const boolQueryBuilder = new BoolQueryBuilder();
const channelQueryBuilder = new TextQueryBuilder();
const topicQueryBuilder = new TextQueryBuilder();
const titleQueryBuilder = new TextQueryBuilder();
const timestampQueryBuilder = new RangeQueryBuilder();

channelQueryBuilder.fields(Field.Channel).text('ARD');
topicQueryBuilder.fields(Field.Topic).text('tagesschau24');
titleQueryBuilder.fields(Field.Title).text('Tagesschau Gebärdensprache');
timestampQueryBuilder.field(Field.Timestamp).gte(1509464430).lte('now+1h/m');

boolQueryBuilder.must(channelQueryBuilder, titleQueryBuilder).not(topicQueryBuilder).filter(timestampQueryBuilder);

const query = boolQueryBuilder.build();
```
und da fällt mir auf: mir fehlt noch ein Builder für das Root-Element.
Vielleicht willst du das ja in Python umsetzten.

Ein Server ist noch nicht erreichbar, das kann ich aber morgen, oder vielleicht auch noch heute Abend, aufsetzten.

Ich hoffe ich konnte dir helfen, und falls du noch fragen hast, nur her damit. 
Viel Glück und Spaß 😄

**Comment by YggdrasiI** [comment]
Wunderbar, mit dem Beispiel konnte ich es nachvollziehen und kann mein kleines Kodi-Plugin anpassen.
Extra QueryBuilder-Klassen als zusätzliche Abstraktionsschicht (Verschachteltes Python-Dict-> verschachtelte Objekte -> Json-Struktur) werde ich im Python-Code aber nicht einbauen, da Eingabe und Ausgabe ähnlich strukturiert sind und es nicht für notwendig erachte.

Die letzte Frage ist nur die nach der Server-URL, wenn er verfügbar ist :)

**Comment by bagbag** [comment]
Eigentlich wollte ich den Server vorhin deployen, doch dann ist mir aufgefallen, dass ich noch gar keinen "Exposer" (so nenne ich die Implementierungen¹ um die API von außen zugänglich zu machen :sweat_smile:) für REST habe, sondern bisher nur Socket.IO.

Stattdessen habe ich damit dann angefangen: 63f22a97fcb8bcb4e45eb2eb5b57a1d185811074


¹: geplant bisher: Socket.IO, REST, RSS-Feed

**Comment by bagbag** [comment]
![screenshot from 2017-11-01 18-34-30](https://user-images.githubusercontent.com/4116942/32288182-67a7b988-bf33-11e7-982c-b72315755886.png)

Viel Spaß :smile:

**Comment by YggdrasiI** [comment]
Danke. :) Bisher scheitere ich noch an folgender Fehlermeldung für das Minimalbeispiel. Dabei passt die Syntax doch gemäß deines Screenshots?!
```
{u'error': {u'message': u"Cannot use 'in' operator to search for 'bool' in undefined",
u'name': u'TypeError',
u'stack': u"TypeError: Cannot use 'in' operator to search for 'bool' in undefined
    at bodyToElasticsearchQuery (/home/mediathekviewweb/mediathekviewweb/server/src/search-engine/elasticsearch/query-converter.ts:88:13)
    at Object.queryToElasticsearchQuery [as default] (/home/mediathekviewweb/mediathekviewweb/server/src/search-engine/elasticsearch/query-converter.ts:20:14)
    at ElasticsearchSearchEngine.<anonymous> (/home/mediathekviewweb/mediathekviewweb/server/src/search-engine/elasticsearch/search-engine.ts:62:44)
    at Generator.next (<anonymous>)
    at /home/mediathekviewweb/mediathekviewweb/server/src/search-engine/elasticsearch/search-engine.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/mediathekviewweb/mediathekviewweb/server/src/search-engine/elasticsearch/search-engine.ts:3:12)
    at ElasticsearchSearchEngine.search (/home/mediathekviewweb/mediathekviewweb/server/src/search-engine/elasticsearch/search-engine.ts:59:16)
    at BaseMediathekViewWebAPI.<anonymous> (/home/mediathekviewweb/mediathekviewweb/server/src/api/api.ts:20:44)
    at Generator.next (<anonymous>)"}}
```
Der Input war
```
{"body": {"text": {"operator": "and", "fields": ["title"], "text": "Tatort"}}, "limit": 10}
```
und gesendet wurde mit
```
    import requests
    import json
    sQueryObj = json.dumps(queryObj)

    url = u"https://testing.mediathekviewweb.de/api/v2/query/json"
    print("Query: " + sQueryObj)
    try:
        r = requests.post(url, data=sQueryObj)
    except:
        pass
```

**Comment by bagbag** [comment]
Du musst noch den Content-Type auf "application/json" setzten

**Comment by YggdrasiI** [comment]
Stimmt, das war das Problem.

**Comment by YggdrasiI** [comment]
Ich habe den Unstable-Branch meines [Plugins](https://github.com/YggdrasiI/plugin.video.simple_mediathek_de) jetzt auf die neue REST-API des Testservers umgestellt und schließe den Issue ab. 

Noch einmal Danke für deine Hilfe + MWV.de
