### ISSUE TITLE
Angaben im Impressum fehlerhaft

### ISSUE THREAD

**Issue by hannesw** [mediathekview/mediathekviewweb#87]
Auf folgender Seite sind die Angaben noch Platzhalter:

https://mediathekviewweb.de/impressum
![image](https://user-images.githubusercontent.com/1560010/33501649-a299abfc-d6dd-11e7-998c-e5528a658140.png)

Das könnte u. U. bei einem übereifrigen Juristen zum Problem werden :worried:

**Comment by bagbag** [comment]
Öh, in der tat nicht ganz korrekt :D Da habe ich beim Deployment auf dem neuen Server nicht dran gedacht das wieder anzupassen. Ich danke dir vielmals 😄

**Comment by bagbag** [comment]
Angepasst.
