### ISSUE TITLE
Wrong Title at KiKA

### ISSUE THREAD

**Issue by gr4ssi** [mediathekview/mediathekviewweb#89]
When I open the web-thing today, I see a show from Yakari and one from Wickie both with the same title, which is highly unlikely.

![image](https://user-images.githubusercontent.com/19840345/33654654-0eda4420-da71-11e7-849c-c305d668e416.png)

**Comment by gr4ssi** [comment]
It's actually the Yakari titel.
Wickie is either "72. Der Käsekrieg", or "71. Der heimliche Schatz" .

**Comment by pidoubleyou** [comment]
Thx. 
That's a bug in the MServer component which creates the film lists.
I moved this issue to https://github.com/mediathekview/MServer/issues/303
