### ISSUE TITLE
Feature Request: better filenames

### ISSUE THREAD

**Issue by klaholwischer** [mediathekview/mediathekviewweb#93]
When I save a movie,  I get the cryptic filename from the television station. Is it possible to change it to the title of the movie?

**Comment by alex1702** [comment]
no, because you download the file directly from the television station.

**Comment by bagbag** [comment]
As Alex said indirectly, unfortunately I don't have any influence on the filename except for Safari, which respects the tag I set.

The best you can do is right click, select save as and change the name.

**Comment by klaholwischer** [comment]
When I select "Link speichern unter" with Windows 10 and Chrome 63, I get a perfect name suggested. Great.

**Comment by bagbag** [comment]
Oh really? So Chrome at least takes my suggestion for that way. Good to know.
