### ISSUE TITLE
Fonko

### ISSUE THREAD

**Issue by ewp17** [mediathekview/mediathekviewweb#94]
Hi,
there es currently a three piece series about an African music trend called Fonko at arte.
The film list contains only one of those three videos (the one on Ghana and Angola). The videos on french-speaking West Africa

https://www.arte.tv/de/videos/078223-002-A/fonko/

and on South Africa and Nigeria

https://www.arte.tv/de/videos/078223-001-A/fonko/

doesn't appear in the list.

Best Regards

**Comment by Nicklas2751** [comment]
Wrong project and please use the forum: https://forum.mediathekview.de/category/7/fehlende-sendungen
