### ISSUE TITLE
Replace Google Fonts

### ISSUE THREAD

**Issue by hajika** [mediathekview/mediathekviewweb#95]
Could you provide a solution that works without google fonts? I'am blocking it and I don't want to unblock it and be tracked by google. Just now, the popup looks like this:

![screenshot_2018-01-26_19-47-44](https://user-images.githubusercontent.com/27491258/35455366-e8285860-02d1-11e8-824c-f18a7c25199f.png)

ok one could say, just unblock google, but I hope there is a privacy friendly solution, because you could just load the pics from your one server as well or provide smaller/working textes in case the font is not loaded.

**Comment by bagbag** [comment]
I hope this is well enough: 17cddddcefd1f5b1f8b4dd619782650dc035d571

It's self hosted now.

**Comment by WebworkrNet** [comment]
https://google-webfonts-helper.herokuapp.com/fonts and https://www.fontsquirrel.com are recommended by https://www.kuketz-blog.de/empfehlungsecke/#google-alternativen.
