### ISSUE TITLE
"Ku'damm" kann nicht gesucht werden (ist aber vorhanden)

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#98]
Suche mit ```Ku'damm``` gibt keine Ergebnisse, mit ```damm```wohl.

**Comment by bagbag** [comment]
Gelöst: 8f3350fe773cc9ff2a81faa2e1edc85c587c788d

**Comment by Wikinaut** [comment]
Danke. Hoffentlich gibt es keine negativen Seiteneffekte.........
