### ISSUE TITLE
[Suggestion] Show availability time: available until ... (date)

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/mediathekviewweb#99]
I do not know if this is possible, but a further enhancement would be the display of the availabilty time ("Dieses Video ist verfügbar bis....").

**Comment by bagbag** [comment]
As the "filmlist" doesn't contains this information, it's not possible.
You have to create an issue at [MLib](https://github.com/mediathekview/MLib) for that.

**Comment by Wikinaut** [comment]
Thanks. I expected that and will do so.
